-- =============================================================================
-- 004-dang-ky-nhan-hang.sql — Quản lý nhà sơ chế > Đăng ký nhận hàng
-- Số hoá "Phiếu đăng ký nhận hàng" (xe/cont ra vào cổng farm): giờ đăng ký, giờ vào/ra
-- thực tế, ảnh, và hàng hoá xuất (mỗi thùng quét QR = 1 dòng; bảng con là TUỲ CHỌN).
-- Khớp features/quan-ly-nha-so-che/dang-ky-nhan-hang.
--
-- Chạy: bash scripts/db-sql.sh -f docs/migrations/004-dang-ky-nhan-hang.sql
-- =============================================================================

BEGIN;

-- 1) Phiếu -------------------------------------------------------------------
CREATE TABLE public.fp_farm_dang_ky_nhan_hang (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_chi_nhanh bigint NOT NULL REFERENCES public.fp_var_chi_nhanh(id) ON DELETE RESTRICT,
    ngay_dang_ky date NOT NULL,
    khach_hang text,
    loai_hang_hoa text,
    so_xe text,
    so_cont text,
    ten_tai_xe text,
    sdt_tai_xe text,
    gio_dang_ky_tu time without time zone,
    gio_dang_ky_den time without time zone,
    tg_vao_thuc_te timestamp with time zone,
    tg_ra_thuc_te timestamp with time zone,
    id_nguoi_check_in bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    id_nguoi_check_out bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    trang_thai text DEFAULT 'cho_vao'::text NOT NULL,
    ghi_chu text,
    hinh_anh_urls text[] DEFAULT ARRAY[]::text[] NOT NULL,
    id_nguoi_tao bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    tg_tao timestamp with time zone DEFAULT now() NOT NULL,
    tg_cap_nhat timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fp_farm_dknh_trang_thai_check
      CHECK (trang_thai = ANY (ARRAY['cho_vao'::text, 'da_vao'::text, 'da_ra'::text, 'huy'::text])),
    CONSTRAINT fp_farm_dknh_vao_ra_check
      CHECK (tg_ra_thuc_te IS NULL OR tg_vao_thuc_te IS NULL OR tg_ra_thuc_te >= tg_vao_thuc_te)
);

COMMENT ON TABLE public.fp_farm_dang_ky_nhan_hang IS 'Phiếu đăng ký nhận hàng: xe/cont ra vào cổng farm';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang.gio_dang_ky_tu IS 'Giờ đăng ký "từ giờ" (theo ngay_dang_ky)';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang.gio_dang_ky_den IS 'Giờ đăng ký "đến giờ" (theo ngay_dang_ky)';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang.tg_vao_thuc_te IS 'Check in: thời điểm xe vào thực tế';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang.tg_ra_thuc_te IS 'Check out: thời điểm xe ra thực tế';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang.trang_thai IS 'cho_vao | da_vao | da_ra | huy';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang.hinh_anh_urls IS 'Mảng URL ảnh (Cloudinary), thứ tự = thứ tự hiển thị';

CREATE INDEX idx_fp_farm_dknh_ngay ON public.fp_farm_dang_ky_nhan_hang USING btree (ngay_dang_ky DESC);
CREATE INDEX idx_fp_farm_dknh_chi_nhanh_trang_thai ON public.fp_farm_dang_ky_nhan_hang USING btree (id_chi_nhanh, trang_thai);

CREATE TRIGGER trg_update_tg_cap_nhat BEFORE UPDATE ON public.fp_farm_dang_ky_nhan_hang
  FOR EACH ROW EXECUTE FUNCTION public.update_tg_cap_nhat_column();

-- 2) Hàng hoá xuất (mỗi thùng 1 dòng) ----------------------------------------
CREATE TABLE public.fp_farm_dang_ky_nhan_hang_ct (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_phieu bigint NOT NULL REFERENCES public.fp_farm_dang_ky_nhan_hang(id) ON DELETE CASCADE,
    id_hang_hoa bigint NOT NULL REFERENCES public.fp_mh_danh_sach_hang_hoa(id) ON DELETE RESTRICT,
    ma_hang_hoa text,
    so_luong numeric(18,4) DEFAULT 1 NOT NULL,
    nguon text DEFAULT 'tay'::text NOT NULL,
    tg_quet timestamp with time zone DEFAULT now() NOT NULL,
    id_nguoi_quet bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    CONSTRAINT fp_farm_dknh_ct_so_luong_check CHECK (so_luong > 0),
    CONSTRAINT fp_farm_dknh_ct_nguon_check CHECK (nguon = ANY (ARRAY['quet'::text, 'tay'::text]))
);

COMMENT ON TABLE public.fp_farm_dang_ky_nhan_hang_ct IS 'Hàng hoá xuất của phiếu đăng ký nhận hàng — mỗi thùng quét QR là 1 dòng (tuỳ chọn)';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang_ct.ma_hang_hoa IS 'Chụp lại mã hàng lúc quét/nhập';
COMMENT ON COLUMN public.fp_farm_dang_ky_nhan_hang_ct.nguon IS 'quet = quét QR; tay = chọn combobox';

CREATE INDEX idx_fp_farm_dknh_ct_phieu ON public.fp_farm_dang_ky_nhan_hang_ct USING btree (id_phieu);
CREATE INDEX idx_fp_farm_dknh_ct_hang_hoa ON public.fp_farm_dang_ky_nhan_hang_ct USING btree (id_hang_hoa);

-- 3) View tổng theo phiếu + hàng hoá (thống kê, tóm tắt trong chi tiết) --------
CREATE VIEW public.v_farm_dang_ky_nhan_hang_tong_hh WITH (security_invoker='true') AS
SELECT ct.id_phieu,
       ct.id_hang_hoa,
       hh.ma_hang_hoa,
       hh.ten_hang_hoa,
       hh.dvt,
       count(*)::integer AS so_dong,
       sum(ct.so_luong) AS tong_so_luong
FROM public.fp_farm_dang_ky_nhan_hang_ct ct
LEFT JOIN public.fp_mh_danh_sach_hang_hoa hh ON hh.id = ct.id_hang_hoa
GROUP BY ct.id_phieu, ct.id_hang_hoa, hh.ma_hang_hoa, hh.ten_hang_hoa, hh.dvt;

-- 4) RLS + grant (giống các bảng fp_farm_* khác của nhóm) ---------------------
ALTER TABLE public.fp_farm_dang_ky_nhan_hang ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_dknh_select_auth ON public.fp_farm_dang_ky_nhan_hang FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_dknh_insert_auth ON public.fp_farm_dang_ky_nhan_hang FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY fp_farm_dknh_update_auth ON public.fp_farm_dang_ky_nhan_hang FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY fp_farm_dknh_delete_auth ON public.fp_farm_dang_ky_nhan_hang FOR DELETE TO authenticated USING (true);

ALTER TABLE public.fp_farm_dang_ky_nhan_hang_ct ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_dknh_ct_select_auth ON public.fp_farm_dang_ky_nhan_hang_ct FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_dknh_ct_insert_auth ON public.fp_farm_dang_ky_nhan_hang_ct FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY fp_farm_dknh_ct_update_auth ON public.fp_farm_dang_ky_nhan_hang_ct FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY fp_farm_dknh_ct_delete_auth ON public.fp_farm_dang_ky_nhan_hang_ct FOR DELETE TO authenticated USING (true);

GRANT ALL ON TABLE public.fp_farm_dang_ky_nhan_hang TO authenticated;
GRANT ALL ON TABLE public.fp_farm_dang_ky_nhan_hang_ct TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_dang_ky_nhan_hang_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_dang_ky_nhan_hang_ct_id_seq TO authenticated;
GRANT SELECT ON TABLE public.v_farm_dang_ky_nhan_hang_tong_hh TO authenticated;

-- 5) Quyền app: chép y nguyên quyền từng chức vụ của "Báo cáo sơ chế" -----------
INSERT INTO public.fp_var_phan_quyen (chuc_vu_id, module_id, actions)
SELECT chuc_vu_id, 'quan-ly-nha-so-che/dang-ky-nhan-hang', actions
FROM public.fp_var_phan_quyen
WHERE module_id = 'quan-ly-nha-so-che/bao-cao-so-che'
ON CONFLICT (chuc_vu_id, module_id) DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';
