-- =============================================================================
-- 009-giam-sat-chat-luong.sql — Quản lý nhà sơ chế > Giám sát chất lượng
-- Mỗi phiếu = 1 cây hàng (pallet). Lấy ngẫu nhiên N thùng mẫu (mặc định 10/60), mỗi thùng
-- 1 tem QR riêng. Quét tem → chấm bộ tiêu chí cho đúng thùng đó. Ngưỡng tính trên tổng
-- các thùng mẫu; kết luận ĐẠT / KHÔNG ĐẠT do app tính (core/ket-luan.ts) rồi ghi lại.
-- Khớp features/quan-ly-nha-so-che/giam-sat-chat-luong.
--
-- Chạy: bash scripts/db-sql.sh -v ON_ERROR_STOP=1 -f docs/migrations/009-giam-sat-chat-luong.sql
-- =============================================================================

BEGIN;

-- 1) Danh mục tiêu chí (cấu hình ở popup Cài đặt của module) ---------------------
CREATE TABLE public.fp_farm_gscl_tieu_chi (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma text NOT NULL UNIQUE,
    ten text NOT NULL,
    loai text NOT NULL,
    don_vi text,
    nguong_min numeric(18,4),
    nguong_max numeric(18,4),
    thu_tu integer DEFAULT 0 NOT NULL,
    dang_dung boolean DEFAULT true NOT NULL,
    tg_tao timestamp with time zone DEFAULT now() NOT NULL,
    tg_cap_nhat timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fp_farm_gscl_tc_loai_check
      CHECK (loai = ANY (ARRAY['dem_loi'::text, 'do_luong'::text, 'dat_khong'::text])),
    CONSTRAINT fp_farm_gscl_tc_nguong_check
      CHECK (nguong_min IS NULL OR nguong_max IS NULL OR nguong_min <= nguong_max)
);

COMMENT ON TABLE public.fp_farm_gscl_tieu_chi IS 'Giám sát chất lượng: danh mục tiêu chí chấm thùng mẫu';
COMMENT ON COLUMN public.fp_farm_gscl_tieu_chi.ma IS 'Khoá trong ket_qua của từng thùng — không đổi sau khi tạo';
COMMENT ON COLUMN public.fp_farm_gscl_tieu_chi.loai IS
  'dem_loi: đếm trái lỗi, ngưỡng = tổng tối đa cho 10 thùng | do_luong: số đo, ngưỡng = khoảng min–max của trung bình | dat_khong: số thùng "Không" tối đa';
COMMENT ON COLUMN public.fp_farm_gscl_tieu_chi.nguong_max IS 'NULL cả min và max = chỉ ghi số, không xét đạt';

CREATE TRIGGER trg_update_tg_cap_nhat BEFORE UPDATE ON public.fp_farm_gscl_tieu_chi
  FOR EACH ROW EXECUTE FUNCTION public.update_tg_cap_nhat_column();

INSERT INTO public.fp_farm_gscl_tieu_chi (ma, ten, loai, don_vi, thu_tu) VALUES
  ('so_trai_tren_nhanh', 'Số trái trên nhánh',     'do_luong',  'trái', 1),
  ('so_kg_tren_nhanh',   'Số kg trên nhánh / nải', 'do_luong',  'kg',   2),
  ('can_dap_dong_goi',   'Cấn dập đóng gói',       'dem_loi',   'trái', 3),
  ('tray_tuoi_nang',     'Trầy tươi nặng',         'dem_loi',   'trái', 4),
  ('tray_tuoi_tb',       'Trầy tươi trung bình',   'dem_loi',   'trái', 5),
  ('tray_kho_nang',      'Trầy khô nặng',          'dem_loi',   'trái', 6),
  ('tray_kho_tb',        'Trầy khô trung bình',    'dem_loi',   'trái', 7),
  ('chin_chin_xanh',     'Chín / chín xanh',       'dem_loi',   'trái', 8),
  ('rep_sap',            'Rệp sáp',                'dem_loi',   'trái', 9),
  ('dan_tem',            'Dán tem',                'dat_khong', NULL,   10),
  ('up_nap',             'Úp nắp',                 'dat_khong', NULL,   11)
ON CONFLICT (ma) DO NOTHING;

-- 2) Phiếu (mỗi phiếu = 1 cây hàng) ---------------------------------------------
CREATE TABLE public.fp_farm_giam_sat_chat_luong (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_phieu text UNIQUE,
    ngay date DEFAULT CURRENT_DATE NOT NULL,
    id_chi_nhanh bigint NOT NULL REFERENCES public.fp_var_chi_nhanh(id) ON DELETE RESTRICT,
    id_hang_hoa bigint REFERENCES public.fp_mh_danh_sach_hang_hoa(id) ON DELETE RESTRICT,
    ma_cay_hang text,
    so_thung_cay integer DEFAULT 60 NOT NULL,
    so_thung_mau integer DEFAULT 10 NOT NULL,
    tieu_chi jsonb DEFAULT '[]'::jsonb NOT NULL,
    trang_thai text DEFAULT 'dang_kiem'::text NOT NULL,
    ket_luan text,
    ghi_chu text,
    id_nguoi_tao bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    tg_tao timestamp with time zone DEFAULT now() NOT NULL,
    tg_cap_nhat timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fp_farm_gscl_so_thung_check
      CHECK (so_thung_cay > 0 AND so_thung_mau BETWEEN 1 AND 100 AND so_thung_mau <= so_thung_cay),
    CONSTRAINT fp_farm_gscl_trang_thai_check
      CHECK (trang_thai = ANY (ARRAY['dang_kiem'::text, 'hoan_thanh'::text, 'huy'::text])),
    CONSTRAINT fp_farm_gscl_ket_luan_check
      CHECK (ket_luan IS NULL OR ket_luan = ANY (ARRAY['dat'::text, 'khong_dat'::text]))
);

COMMENT ON TABLE public.fp_farm_giam_sat_chat_luong IS 'Phiếu giám sát chất lượng: mỗi phiếu là một cây hàng, kiểm N thùng mẫu';
COMMENT ON COLUMN public.fp_farm_giam_sat_chat_luong.so_phieu IS 'Trigger sinh GS-00001 theo id';
COMMENT ON COLUMN public.fp_farm_giam_sat_chat_luong.tieu_chi IS 'Ảnh chụp bộ tiêu chí + ngưỡng lúc tạo phiếu (sửa danh mục không làm sai phiếu cũ)';
COMMENT ON COLUMN public.fp_farm_giam_sat_chat_luong.ket_luan IS 'dat | khong_dat — app tính theo ngưỡng khi đủ thùng mẫu';

CREATE INDEX idx_fp_farm_gscl_ngay ON public.fp_farm_giam_sat_chat_luong USING btree (ngay DESC);
CREATE INDEX idx_fp_farm_gscl_chi_nhanh_trang_thai ON public.fp_farm_giam_sat_chat_luong USING btree (id_chi_nhanh, trang_thai);

CREATE TRIGGER trg_update_tg_cap_nhat BEFORE UPDATE ON public.fp_farm_giam_sat_chat_luong
  FOR EACH ROW EXECUTE FUNCTION public.update_tg_cap_nhat_column();

-- Số phiếu + ảnh chụp tiêu chí khi tạo.
CREATE FUNCTION public.fn_farm_gscl_truoc_khi_tao() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF NEW.so_phieu IS NULL OR btrim(NEW.so_phieu) = '' THEN
    NEW.so_phieu := 'GS-' || lpad(NEW.id::text, 5, '0');
  END IF;
  IF NEW.tieu_chi IS NULL OR NEW.tieu_chi = '[]'::jsonb THEN
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
             'ma', tc.ma, 'ten', tc.ten, 'loai', tc.loai, 'don_vi', tc.don_vi,
             'nguong_min', tc.nguong_min, 'nguong_max', tc.nguong_max
           ) ORDER BY tc.thu_tu, tc.id), '[]'::jsonb)
      INTO NEW.tieu_chi
      FROM public.fp_farm_gscl_tieu_chi tc
     WHERE tc.dang_dung;
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER trg_farm_gscl_truoc_khi_tao BEFORE INSERT ON public.fp_farm_giam_sat_chat_luong
  FOR EACH ROW EXECUTE FUNCTION public.fn_farm_gscl_truoc_khi_tao();

-- 3) Thùng mẫu (mỗi thùng 1 dòng, 1 tem) ------------------------------------------
CREATE TABLE public.fp_farm_giam_sat_chat_luong_ct (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_phieu bigint NOT NULL REFERENCES public.fp_farm_giam_sat_chat_luong(id) ON DELETE CASCADE,
    stt_thung integer NOT NULL,
    ma_tem text NOT NULL UNIQUE,
    ket_qua jsonb DEFAULT '{}'::jsonb NOT NULL,
    da_kiem boolean DEFAULT false NOT NULL,
    tg_kiem timestamp with time zone,
    id_nguoi_kiem bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    ghi_chu text,
    CONSTRAINT fp_farm_gscl_ct_stt_check CHECK (stt_thung >= 1),
    CONSTRAINT fp_farm_gscl_ct_phieu_stt_key UNIQUE (id_phieu, stt_thung)
);

COMMENT ON TABLE public.fp_farm_giam_sat_chat_luong_ct IS 'Thùng mẫu của phiếu giám sát chất lượng — sinh sẵn theo so_thung_mau';
COMMENT ON COLUMN public.fp_farm_giam_sat_chat_luong_ct.ma_tem IS 'Nội dung QR trên tem: <so_phieu>-<stt> (app thêm tiền tố GSCL:)';
COMMENT ON COLUMN public.fp_farm_giam_sat_chat_luong_ct.ket_qua IS '{ma_tieu_chi: số | true/false}';

-- Sinh / cắt dòng thùng theo so_thung_mau. Không cho cắt thùng đã kiểm.
CREATE FUNCTION public.fn_farm_gscl_dong_bo_thung() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.fp_farm_giam_sat_chat_luong_ct
     WHERE id_phieu = NEW.id AND stt_thung > NEW.so_thung_mau AND da_kiem
  ) THEN
    RAISE EXCEPTION 'Không giảm số thùng mẫu xuống % được: đã có thùng số lớn hơn được kiểm', NEW.so_thung_mau
      USING ERRCODE = 'P0001';
  END IF;

  DELETE FROM public.fp_farm_giam_sat_chat_luong_ct
   WHERE id_phieu = NEW.id AND stt_thung > NEW.so_thung_mau;

  INSERT INTO public.fp_farm_giam_sat_chat_luong_ct (id_phieu, stt_thung, ma_tem)
  SELECT NEW.id, g, NEW.so_phieu || '-' || lpad(g::text, 2, '0')
    FROM generate_series(1, NEW.so_thung_mau) AS g
  ON CONFLICT (id_phieu, stt_thung) DO NOTHING;

  RETURN NULL;
END
$$;

CREATE TRIGGER trg_farm_gscl_dong_bo_thung
  AFTER INSERT OR UPDATE OF so_thung_mau ON public.fp_farm_giam_sat_chat_luong
  FOR EACH ROW EXECUTE FUNCTION public.fn_farm_gscl_dong_bo_thung();

CREATE INDEX idx_fp_farm_gscl_ct_phieu ON public.fp_farm_giam_sat_chat_luong_ct USING btree (id_phieu);

-- 4) RLS + grant (giống các bảng fp_farm_* khác của nhóm) ---------------------------
ALTER TABLE public.fp_farm_gscl_tieu_chi ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_gscl_tc_select_auth ON public.fp_farm_gscl_tieu_chi FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_gscl_tc_insert_auth ON public.fp_farm_gscl_tieu_chi FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY fp_farm_gscl_tc_update_auth ON public.fp_farm_gscl_tieu_chi FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY fp_farm_gscl_tc_delete_auth ON public.fp_farm_gscl_tieu_chi FOR DELETE TO authenticated USING (true);

ALTER TABLE public.fp_farm_giam_sat_chat_luong ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_gscl_select_auth ON public.fp_farm_giam_sat_chat_luong FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_gscl_insert_auth ON public.fp_farm_giam_sat_chat_luong FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY fp_farm_gscl_update_auth ON public.fp_farm_giam_sat_chat_luong FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY fp_farm_gscl_delete_auth ON public.fp_farm_giam_sat_chat_luong FOR DELETE TO authenticated USING (true);

ALTER TABLE public.fp_farm_giam_sat_chat_luong_ct ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_gscl_ct_select_auth ON public.fp_farm_giam_sat_chat_luong_ct FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_gscl_ct_insert_auth ON public.fp_farm_giam_sat_chat_luong_ct FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY fp_farm_gscl_ct_update_auth ON public.fp_farm_giam_sat_chat_luong_ct FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY fp_farm_gscl_ct_delete_auth ON public.fp_farm_giam_sat_chat_luong_ct FOR DELETE TO authenticated USING (true);

GRANT ALL ON TABLE public.fp_farm_gscl_tieu_chi TO authenticated;
GRANT ALL ON TABLE public.fp_farm_giam_sat_chat_luong TO authenticated;
GRANT ALL ON TABLE public.fp_farm_giam_sat_chat_luong_ct TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_gscl_tieu_chi_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_giam_sat_chat_luong_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_giam_sat_chat_luong_ct_id_seq TO authenticated;

-- 5) Quyền app: chép y nguyên quyền từng chức vụ của "Báo cáo sơ chế" -----------------
INSERT INTO public.fp_var_phan_quyen (chuc_vu_id, module_id, actions)
SELECT chuc_vu_id, 'quan-ly-nha-so-che/giam-sat-chat-luong', actions
FROM public.fp_var_phan_quyen
WHERE module_id = 'quan-ly-nha-so-che/bao-cao-so-che'
ON CONFLICT (chuc_vu_id, module_id) DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';
