-- =============================================================================
-- 012-google-sheets-dong-bo.sql — Đồng bộ Google Sheet tự động (giai đoạn 3)
--
-- Lịch đồng bộ: định kỳ (mỗi giờ / 4 giờ / ngày / tuần / tháng) hoặc "khi có thay đổi".
-- "Khi có thay đổi" = trigger FOR EACH STATEMENT trên bảng gốc bật cờ `can_chay` +
-- pg_notify; worker services/sheets ghi sau cửa sổ chờ 5 phút tính từ thay đổi ĐẦU TIÊN
-- (Google giới hạn ~60 lệnh ghi/phút/người), và đối soát toàn bộ lúc 03:00 hằng đêm.
--
-- Worker đọc dữ liệu nguồn qua PostgREST bằng JWT của NGƯỜI TẠO LỊCH (RLS áp như trên
-- app) — role sheets_service không có quyền đọc bảng nghiệp vụ nào.
-- Chỉ người có TOÀN PHẠM VI trên module (cap_bac = 1 hoặc quyền admin/all) mới tạo được
-- lịch: RLS các bảng này mở cho mọi người đăng nhập, phạm vi "của tôi/chi nhánh tôi" chỉ
-- là bộ lọc ở UI — lịch chạy nền không áp được bộ lọc đó.
--
-- Chạy SAU 011: bash scripts/db-sql.sh -v ON_ERROR_STOP=1 -f docs/migrations/012-google-sheets-dong-bo.sql
-- =============================================================================

BEGIN;

-- 1) Lịch đồng bộ ------------------------------------------------------------------
CREATE TABLE public.fp_var_dong_bo_sheet (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Ngắt kết nối Google = xoá kết nối = xoá luôn lịch của người đó.
    nhan_vien_id bigint NOT NULL REFERENCES public.fp_var_google_ket_noi(nhan_vien_id) ON DELETE CASCADE,
    module_id text NOT NULL,
    -- Bảng/view đọc qua PostgREST; server tra từ danh sách cho phép theo module_id, client không tự đặt.
    nguon text NOT NULL,
    -- Bảng gắn trigger đánh dấu (view phải liệt kê mọi bảng nền ảnh hưởng tới số liệu).
    bang_goc text[] NOT NULL,
    -- [{key, label, type}] — cột đầu luôn là `id` (khoá để cập nhật đúng dòng).
    cot jsonb NOT NULL,
    spreadsheet_id text NOT NULL,
    spreadsheet_url text NOT NULL,
    ten_file text,
    sheet_title text NOT NULL,
    tan_suat text NOT NULL,
    gio smallint,
    thu smallint,
    ngay_thang smallint,
    bat boolean DEFAULT true NOT NULL,
    lan_chay_ke_tiep timestamp with time zone,
    can_chay boolean DEFAULT false NOT NULL,
    thay_doi_dau_luc timestamp with time zone,
    doi_soat_ke_tiep timestamp with time zone,
    -- Khoá thuê (lease): worker nào đang chạy lịch này; quá 15 phút coi như worker chết.
    dang_chay_tu timestamp with time zone,
    -- SHA-256 của header + dữ liệu lần ghi gần nhất — giống hệt thì bỏ qua, khỏi gọi Google.
    van_tay text,
    lan_chay_cuoi timestamp with time zone,
    ket_qua_cuoi text,
    thong_diep_cuoi text,
    so_dong_cuoi integer,
    so_loi_lien_tiep integer DEFAULT 0 NOT NULL,
    tg_tao timestamp with time zone DEFAULT now() NOT NULL,
    tg_cap_nhat timestamp with time zone DEFAULT now() NOT NULL,
    -- Hai lịch cùng ghi một tab là ghi đè lẫn nhau.
    CONSTRAINT fp_var_dong_bo_sheet_dich_uniq UNIQUE (spreadsheet_id, sheet_title),
    CONSTRAINT fp_var_dong_bo_sheet_tan_suat_check CHECK (tan_suat = ANY (ARRAY[
      'khi_thay_doi'::text, 'moi_gio'::text, 'moi_4_gio'::text, 'hang_ngay'::text, 'hang_tuan'::text, 'hang_thang'::text])),
    CONSTRAINT fp_var_dong_bo_sheet_gio_check CHECK (gio IS NULL OR gio BETWEEN 0 AND 23),
    CONSTRAINT fp_var_dong_bo_sheet_thu_check CHECK (thu IS NULL OR thu BETWEEN 1 AND 7),
    CONSTRAINT fp_var_dong_bo_sheet_ngay_check CHECK (ngay_thang IS NULL OR ngay_thang BETWEEN 1 AND 31),
    CONSTRAINT fp_var_dong_bo_sheet_ket_qua_check CHECK (ket_qua_cuoi IS NULL OR ket_qua_cuoi = ANY (ARRAY['ok'::text, 'loi'::text]))
);

COMMENT ON TABLE public.fp_var_dong_bo_sheet IS
  'Lịch đồng bộ Google Sheet (services/sheets). Chỉ service đọc/ghi; người dùng thao tác qua /sheets/lich.';

CREATE INDEX fp_var_dong_bo_sheet_nhan_vien_idx ON public.fp_var_dong_bo_sheet (nhan_vien_id);
-- Trigger đánh dấu tìm theo bảng gốc trên mỗi câu lệnh ghi — phải rẻ.
CREATE INDEX fp_var_dong_bo_sheet_bang_goc_idx ON public.fp_var_dong_bo_sheet USING gin (bang_goc)
  WHERE bat AND tan_suat = 'khi_thay_doi';

ALTER TABLE public.fp_var_dong_bo_sheet ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.fp_var_dong_bo_sheet FROM PUBLIC, anon, authenticated;
CREATE POLICY "Service sheets toàn quyền lịch" ON public.fp_var_dong_bo_sheet
  TO sheets_service USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_var_dong_bo_sheet TO sheets_service;

-- 2) Trigger "khi có thay đổi" ------------------------------------------------------
-- FOR EACH STATEMENT: một lệnh sửa 1.000 dòng chỉ bật cờ một lần. `NOT can_chay` để
-- lệnh ghi liên tiếp không UPDATE lại cùng dòng lịch (tránh tranh khoá với worker).
CREATE FUNCTION public.fn_dong_bo_sheet_danh_dau() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  UPDATE public.fp_var_dong_bo_sheet
     SET can_chay = true,
         thay_doi_dau_luc = COALESCE(thay_doi_dau_luc, now())
   WHERE bat
     AND tan_suat = 'khi_thay_doi'
     AND bang_goc @> ARRAY[TG_TABLE_NAME::text]
     AND NOT can_chay;
  IF FOUND THEN
    PERFORM pg_notify('dong_bo_sheet', TG_TABLE_NAME);
  END IF;
  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_dong_bo_sheet_danh_dau() FROM PUBLIC;

-- Bảng gốc của 2 module thí điểm. Đấu thêm module: thêm CREATE TRIGGER như dưới +
-- một view v_xuat_<module> + một mục trong services/sheets/src/core/nguon-dong-bo.ts.
CREATE TRIGGER trg_dong_bo_sheet_danh_dau
  AFTER INSERT OR UPDATE OR DELETE ON public.fp_mh_don_dat_hang
  FOR EACH STATEMENT EXECUTE FUNCTION public.fn_dong_bo_sheet_danh_dau();
CREATE TRIGGER trg_dong_bo_sheet_danh_dau
  AFTER INSERT OR UPDATE OR DELETE ON public.fp_farm_phieu_kho_phan_thuoc
  FOR EACH STATEMENT EXECUTE FUNCTION public.fn_dong_bo_sheet_danh_dau();
CREATE TRIGGER trg_dong_bo_sheet_danh_dau
  AFTER INSERT OR UPDATE OR DELETE ON public.fp_farm_phieu_kho_phan_thuoc_chi_tiet
  FOR EACH STATEMENT EXECUTE FUNCTION public.fn_dong_bo_sheet_danh_dau();

-- 3) View nguồn: tên cột = key xuất của module (utils/export-*-danh-sach.ts) ----------
-- security_invoker: đọc bằng quyền người gọi (JWT người tạo lịch), RLS bảng nền áp đúng.
CREATE VIEW public.v_xuat_don_dat_hang WITH (security_invoker='true') AS
SELECT s.id,
       s.so_po,
       s.ngay_dat,
       s.ngay_giao_dk,
       s.trang_thai,
       s.ref_ten_nha_cung_cap AS ten_nha_cung_cap,
       s.ref_ma_nha_cung_cap AS ma_nha_cung_cap,
       s.id_nha_cung_cap,
       s.ref_ten_kho_nhan AS ten_kho_nhan,
       s.id_kho_nhan,
       s.so_phieu_de_xuat_ref AS so_phieu_de_xuat,
       s.id_phieu_de_xuat_vat_tu,
       s.ref_ten_nguoi_dat AS ten_nguoi_dat,
       s.ref_ma_nguoi_dat AS ma_nguoi_dat,
       s.id_nguoi_dat,
       s.ref_ten_nguoi_duyet AS ten_nguoi_duyet,
       s.ref_ma_nguoi_duyet AS ma_nguoi_duyet,
       s.id_nguoi_duyet,
       NULL::text AS dieu_khoan_thanh_toan,
       s.ghi_chu,
       s.tg_cap_nhat,
       s.tg_tao
  FROM public.v_don_dat_hang_summary s;

CREATE VIEW public.v_xuat_phieu_kho_phan_thuoc WITH (security_invoker='true') AS
SELECT s.id,
       s.so_phieu,
       s.ngay,
       s.loai,
       s.trang_thai,
       s.kho_id,
       COALESCE(s.ref_ten_kho, s.ten_kho) AS ten_kho,
       s.kho_den_id,
       CASE WHEN s.kho_den_id IS NOT NULL THEN COALESCE(s.ref_ten_kho_den, s.ten_kho_den) END AS ten_kho_den,
       s.mo_ta,
       s.trao_doi,
       s.nguoi_tao_id,
       CASE WHEN s.nguoi_tao_id IS NOT NULL THEN COALESCE(s.ten_nguoi_tao, s.ref_ten_nguoi_tao) END AS ten_nguoi_tao,
       s.id_nguoi_duyet,
       CASE WHEN s.id_nguoi_duyet IS NOT NULL THEN s.ref_ten_nguoi_duyet END AS ten_nguoi_duyet,
       s.tg_tao,
       s.tg_cap_nhat,
       s.so_dong AS tong_so_dong,
       s.tong_so_luong,
       s.tong_tien
  FROM public.v_farm_phieu_kho_phan_thuoc_summary s;

GRANT SELECT ON public.v_xuat_don_dat_hang, public.v_xuat_phieu_kho_phan_thuoc TO authenticated;

-- 4) Kiểm người tạo lịch — gọi lúc tạo lịch và MỖI lần chạy -------------------------
-- toan_pham_vi khớp quy ước "cấp cao" của app (useModulePermission + use-*-view-scope).
CREATE FUNCTION public.rpc_sheets_nguoi_tao(p_nhan_vien_id bigint, p_module_id text)
    RETURNS TABLE(email text, con_lam boolean, toan_pham_vi boolean)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT nv.email,
         COALESCE(nv.trang_thai, '') <> 'Nghỉ việc',
         COALESCE(nv.cap_bac = 1, false) OR EXISTS (
           SELECT 1
             FROM public.fp_var_phan_quyen pq
            WHERE pq.chuc_vu_id = nv.chuc_vu_id
              AND pq.module_id = p_module_id
              AND pq.actions && ARRAY['admin', 'all']::text[]
         )
    FROM public.fp_var_nhan_vien nv
   WHERE nv.id = p_nhan_vien_id;
$$;

REVOKE ALL ON FUNCTION public.rpc_sheets_nguoi_tao(bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_sheets_nguoi_tao(bigint, text) TO sheets_service;

-- 5) Báo lỗi đồng bộ vào chuông thông báo — tối đa 1 lần/ngày/lịch -------------------
-- Không đi qua outbox vì đây là sự kiện hệ thống của worker, không phải dữ liệu đổi.
CREATE FUNCTION public.rpc_sheets_bao_loi(p_lich_id bigint, p_tieu_de text, p_noi_dung text)
    RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
  v_lich public.fp_var_dong_bo_sheet;
BEGIN
  SELECT * INTO v_lich FROM public.fp_var_dong_bo_sheet WHERE id = p_lich_id;
  IF NOT FOUND THEN
    RETURN false;
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.fp_var_thong_bao
     WHERE bang = 'fp_var_dong_bo_sheet'
       AND ban_ghi_id = p_lich_id
       AND loai_su_kien = 'dong_bo_sheet_loi'
       AND tg_tao >= date_trunc('day', now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
  ) THEN
    RETURN false;
  END IF;
  INSERT INTO public.fp_var_thong_bao
         (nguoi_nhan_id, module_id, loai_su_kien, muc, tieu_de, noi_dung, link, bang, ban_ghi_id, du_lieu)
  -- link NULL: chuông điều hướng bằng router nội bộ, không mở được URL Google Sheet.
  VALUES (v_lich.nhan_vien_id, v_lich.module_id, 'dong_bo_sheet_loi', 'cao', p_tieu_de, p_noi_dung,
          NULL, 'fp_var_dong_bo_sheet', p_lich_id,
          jsonb_build_object('sheet_title', v_lich.sheet_title, 'ten_file', v_lich.ten_file,
                             'spreadsheet_url', v_lich.spreadsheet_url));
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_sheets_bao_loi(bigint, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_sheets_bao_loi(bigint, text, text) TO sheets_service;

COMMIT;

-- PostgREST nạp lại schema cache để thấy 2 view mới.
NOTIFY pgrst, 'reload schema';
