-- =============================================================================
-- 032-dang-ky-tham-quan.sql — Quản lý nhà sơ chế > Phiếu > Đăng ký tham quan farm
-- Số hoá "Phiếu đăng ký tham quan farm": danh sách khách, thời gian đăng ký, mục đích,
-- phương tiện, người tiếp đón, check in / check out thực tế (cùng luồng với Đăng ký nhận
-- hàng) và ảnh phiếu giấy đã ký. Khớp features/quan-ly-nha-so-che/dang-ky-tham-quan.
--
-- Trước khi chạy: bash scripts/db-backup.sh truoc-032
-- Chạy: bash scripts/db-sql.sh -v ON_ERROR_STOP=1 -f docs/migrations/032-dang-ky-tham-quan.sql
-- =============================================================================

BEGIN;

-- 1) Phiếu -------------------------------------------------------------------
CREATE TABLE public.fp_farm_dang_ky_tham_quan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_chi_nhanh bigint NOT NULL REFERENCES public.fp_var_chi_nhanh(id) ON DELETE RESTRICT,
    ngay_dang_ky date DEFAULT CURRENT_DATE NOT NULL,
    tg_bat_dau timestamp with time zone NOT NULL,
    tg_ket_thuc timestamp with time zone,
    muc_dich text[] DEFAULT ARRAY[]::text[] NOT NULL,
    muc_dich_khac text,
    phuong_tien text,
    nguoi_dai_dien text,
    id_nguoi_tiep_don bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    tg_vao_thuc_te timestamp with time zone,
    tg_ra_thuc_te timestamp with time zone,
    id_nguoi_check_in bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    id_nguoi_check_out bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    trang_thai text DEFAULT 'cho_vao'::text NOT NULL,
    ghi_chu text,
    hinh_anh_urls text[] DEFAULT ARRAY[]::text[] NOT NULL,
    id_nguoi_tao bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
    tg_tao timestamp with time zone DEFAULT now() NOT NULL,
    tg_cap_nhat timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fp_farm_dktq_trang_thai_check
      CHECK (trang_thai = ANY (ARRAY['cho_vao'::text, 'da_vao'::text, 'da_ra'::text, 'huy'::text])),
    CONSTRAINT fp_farm_dktq_muc_dich_check
      CHECK (muc_dich <@ ARRAY['trai_nghiem_nong_nghiep'::text, 'tham_quan_du_lich'::text, 'tham_quan_nsc'::text, 'khac'::text]),
    CONSTRAINT fp_farm_dktq_phuong_tien_check
      CHECK (phuong_tien IS NULL OR phuong_tien = ANY (ARRAY['xe_rieng'::text, 'xe_cong_ty'::text, 'xe_don_nsc'::text])),
    CONSTRAINT fp_farm_dktq_dang_ky_check
      CHECK (tg_ket_thuc IS NULL OR tg_ket_thuc >= tg_bat_dau),
    CONSTRAINT fp_farm_dktq_vao_ra_check
      CHECK (tg_ra_thuc_te IS NULL OR tg_vao_thuc_te IS NULL OR tg_ra_thuc_te >= tg_vao_thuc_te)
);

COMMENT ON TABLE public.fp_farm_dang_ky_tham_quan IS 'Phiếu đăng ký tham quan farm: đoàn/khách, thời gian, mục đích, check in/out';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.tg_bat_dau IS 'Thời gian đăng ký: từ';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.tg_ket_thuc IS 'Thời gian đăng ký: đến';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.muc_dich IS 'Tập con: trai_nghiem_nong_nghiep | tham_quan_du_lich | tham_quan_nsc | khac';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.muc_dich_khac IS 'Ghi rõ khi muc_dich có "khac"';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.phuong_tien IS 'xe_rieng | xe_cong_ty | xe_don_nsc';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.nguoi_dai_dien IS 'Người đại diện đoàn/khách (ký cam kết)';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.id_nguoi_tiep_don IS 'Nhân viên farm tiếp đón / phụ trách đoàn';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.trang_thai IS 'cho_vao | da_vao | da_ra | huy';
COMMENT ON COLUMN public.fp_farm_dang_ky_tham_quan.hinh_anh_urls IS 'Ảnh phiếu giấy đã ký… (/media/f/...), thứ tự = thứ tự hiển thị';

CREATE INDEX idx_fp_farm_dktq_ngay ON public.fp_farm_dang_ky_tham_quan USING btree (ngay_dang_ky DESC);
CREATE INDEX idx_fp_farm_dktq_chi_nhanh_trang_thai ON public.fp_farm_dang_ky_tham_quan USING btree (id_chi_nhanh, trang_thai);

CREATE TRIGGER trg_update_tg_cap_nhat BEFORE UPDATE ON public.fp_farm_dang_ky_tham_quan
  FOR EACH ROW EXECUTE FUNCTION public.update_tg_cap_nhat_column();

-- 2) Khách tham quan (mỗi người 1 dòng) ---------------------------------------
CREATE TABLE public.fp_farm_dang_ky_tham_quan_khach (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_phieu bigint NOT NULL REFERENCES public.fp_farm_dang_ky_tham_quan(id) ON DELETE CASCADE,
    stt integer DEFAULT 1 NOT NULL,
    ho_ten text NOT NULL,
    gioi_tinh text,
    quoc_tich text,
    so_dien_thoai text,
    nguoi_gioi_thieu text,
    khu_vuc_tham_quan text,
    don_vi_lam_viec text,
    CONSTRAINT fp_farm_dktq_khach_ho_ten_check CHECK (btrim(ho_ten) <> ''),
    CONSTRAINT fp_farm_dktq_khach_gioi_tinh_check
      CHECK (gioi_tinh IS NULL OR gioi_tinh = ANY (ARRAY['nam'::text, 'nu'::text, 'khac'::text]))
);

COMMENT ON TABLE public.fp_farm_dang_ky_tham_quan_khach IS 'Khách tham quan của phiếu đăng ký tham quan farm';

CREATE INDEX idx_fp_farm_dktq_khach_phieu ON public.fp_farm_dang_ky_tham_quan_khach USING btree (id_phieu, stt);

-- 3) RLS: đọc mở cho tài khoản đăng nhập (phạm vi chi nhánh lọc ở app như ĐKNH);
--    ghi theo quyền module. Khách là một phần của phiếu → ai tạo / sửa phiếu được thì ghi được.
ALTER TABLE public.fp_farm_dang_ky_tham_quan ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_dktq_select_auth ON public.fp_farm_dang_ky_tham_quan
  FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_dktq_insert_quyen ON public.fp_farm_dang_ky_tham_quan
  FOR INSERT TO authenticated
  WITH CHECK (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['create', 'admin', 'all']));
CREATE POLICY fp_farm_dktq_update_quyen ON public.fp_farm_dang_ky_tham_quan
  FOR UPDATE TO authenticated
  USING (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['update', 'admin', 'all']))
  WITH CHECK (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['update', 'admin', 'all']));
CREATE POLICY fp_farm_dktq_delete_quyen ON public.fp_farm_dang_ky_tham_quan
  FOR DELETE TO authenticated
  USING (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['delete', 'admin', 'all']));

ALTER TABLE public.fp_farm_dang_ky_tham_quan_khach ENABLE ROW LEVEL SECURITY;
CREATE POLICY fp_farm_dktq_khach_select_auth ON public.fp_farm_dang_ky_tham_quan_khach
  FOR SELECT TO authenticated USING (true);
CREATE POLICY fp_farm_dktq_khach_insert_quyen ON public.fp_farm_dang_ky_tham_quan_khach
  FOR INSERT TO authenticated
  WITH CHECK (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['create', 'update', 'admin', 'all']));
CREATE POLICY fp_farm_dktq_khach_update_quyen ON public.fp_farm_dang_ky_tham_quan_khach
  FOR UPDATE TO authenticated
  USING (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['create', 'update', 'admin', 'all']))
  WITH CHECK (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['create', 'update', 'admin', 'all']));
CREATE POLICY fp_farm_dktq_khach_delete_quyen ON public.fp_farm_dang_ky_tham_quan_khach
  FOR DELETE TO authenticated
  USING (public.fn_co_quyen_module('quan-ly-nha-so-che/dang-ky-tham-quan', ARRAY['create', 'update', 'delete', 'admin', 'all']));

REVOKE ALL ON TABLE public.fp_farm_dang_ky_tham_quan FROM PUBLIC, anon;
REVOKE ALL ON TABLE public.fp_farm_dang_ky_tham_quan_khach FROM PUBLIC, anon;
GRANT ALL ON TABLE public.fp_farm_dang_ky_tham_quan TO authenticated;
GRANT ALL ON TABLE public.fp_farm_dang_ky_tham_quan_khach TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_dang_ky_tham_quan_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fp_farm_dang_ky_tham_quan_khach_id_seq TO authenticated;

-- 4) Nhật ký thay đổi (migration 016) -----------------------------------------
CREATE TRIGGER trg_nhat_ky_thay_doi AFTER INSERT OR UPDATE OR DELETE ON public.fp_farm_dang_ky_tham_quan
  FOR EACH ROW EXECUTE FUNCTION public.fn_ghi_nhat_ky_thay_doi();
CREATE TRIGGER trg_nhat_ky_thay_doi AFTER INSERT OR UPDATE OR DELETE ON public.fp_farm_dang_ky_tham_quan_khach
  FOR EACH ROW EXECUTE FUNCTION public.fn_ghi_nhat_ky_thay_doi();

-- 5) RPC lưu phiếu + danh sách khách trong MỘT transaction --------------------
-- SECURITY INVOKER: RLS ở trên vẫn áp với người gọi. p_id NULL = tạo mới.
-- Trạng thái / giờ vào ra / người check in-out KHÔNG đổi qua RPC này (đi luồng chuyển trạng thái).
CREATE OR REPLACE FUNCTION public.rpc_luu_dang_ky_tham_quan(p_id bigint, p_phieu jsonb, p_khach jsonb)
    RETURNS bigint
    LANGUAGE plpgsql SECURITY INVOKER
    SET search_path TO 'public'
    AS $$
DECLARE
  v_id bigint;
  r public.fp_farm_dang_ky_tham_quan;
BEGIN
  r := jsonb_populate_record(NULL::public.fp_farm_dang_ky_tham_quan, p_phieu);

  IF p_id IS NULL THEN
    INSERT INTO public.fp_farm_dang_ky_tham_quan (
      id_chi_nhanh, ngay_dang_ky, tg_bat_dau, tg_ket_thuc, muc_dich, muc_dich_khac, phuong_tien,
      nguoi_dai_dien, id_nguoi_tiep_don, ghi_chu, hinh_anh_urls, id_nguoi_tao
    ) VALUES (
      r.id_chi_nhanh, COALESCE(r.ngay_dang_ky, CURRENT_DATE), r.tg_bat_dau, r.tg_ket_thuc,
      COALESCE(r.muc_dich, ARRAY[]::text[]), r.muc_dich_khac, r.phuong_tien,
      r.nguoi_dai_dien, r.id_nguoi_tiep_don, r.ghi_chu, COALESCE(r.hinh_anh_urls, ARRAY[]::text[]),
      public.nhan_vien_hien_tai_id()
    )
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.fp_farm_dang_ky_tham_quan t
       SET id_chi_nhanh = r.id_chi_nhanh,
           ngay_dang_ky = COALESCE(r.ngay_dang_ky, t.ngay_dang_ky),
           tg_bat_dau = r.tg_bat_dau,
           tg_ket_thuc = r.tg_ket_thuc,
           muc_dich = COALESCE(r.muc_dich, ARRAY[]::text[]),
           muc_dich_khac = r.muc_dich_khac,
           phuong_tien = r.phuong_tien,
           nguoi_dai_dien = r.nguoi_dai_dien,
           id_nguoi_tiep_don = r.id_nguoi_tiep_don,
           ghi_chu = r.ghi_chu,
           hinh_anh_urls = COALESCE(r.hinh_anh_urls, ARRAY[]::text[])
     WHERE t.id = p_id
     RETURNING t.id INTO v_id;
    IF v_id IS NULL THEN
      RAISE EXCEPTION 'Không tìm thấy phiếu tham quan % hoặc không có quyền sửa', p_id USING ERRCODE = 'P0002';
    END IF;
    DELETE FROM public.fp_farm_dang_ky_tham_quan_khach WHERE id_phieu = v_id;
  END IF;

  INSERT INTO public.fp_farm_dang_ky_tham_quan_khach (
    id_phieu, stt, ho_ten, gioi_tinh, quoc_tich, so_dien_thoai, nguoi_gioi_thieu, khu_vuc_tham_quan, don_vi_lam_viec
  )
  SELECT v_id, COALESCE(k.stt, 1), k.ho_ten, k.gioi_tinh, k.quoc_tich, k.so_dien_thoai, k.nguoi_gioi_thieu,
         k.khu_vuc_tham_quan, k.don_vi_lam_viec
  FROM jsonb_populate_recordset(NULL::public.fp_farm_dang_ky_tham_quan_khach, COALESCE(p_khach, '[]'::jsonb)) k;

  RETURN v_id;
END;
$$;

COMMENT ON FUNCTION public.rpc_luu_dang_ky_tham_quan(bigint, jsonb, jsonb) IS
  'Tạo / sửa phiếu đăng ký tham quan kèm thay toàn bộ danh sách khách trong một transaction (RLS áp theo người gọi).';

REVOKE ALL ON FUNCTION public.rpc_luu_dang_ky_tham_quan(bigint, jsonb, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rpc_luu_dang_ky_tham_quan(bigint, jsonb, jsonb) TO authenticated;

-- 6) Quyền app: chép y nguyên quyền từng chức vụ của "Đăng ký nhận hàng" ----------
INSERT INTO public.fp_var_phan_quyen (chuc_vu_id, module_id, actions)
SELECT chuc_vu_id, 'quan-ly-nha-so-che/dang-ky-tham-quan', actions
FROM public.fp_var_phan_quyen
WHERE module_id = 'quan-ly-nha-so-che/dang-ky-nhan-hang'
ON CONFLICT (chuc_vu_id, module_id) DO NOTHING;

-- 7) Dữ liệu mẫu -------------------------------------------------------------
-- Chi nhánh "Farm fp1" (không có thì chi nhánh đầu tiên); người tiếp đón tra theo tên.
DO $$
DECLARE
  v_cn bigint := COALESCE(
    (SELECT id FROM public.fp_var_chi_nhanh WHERE ten_chi_nhanh ILIKE 'Farm fp1' LIMIT 1),
    (SELECT id FROM public.fp_var_chi_nhanh ORDER BY id LIMIT 1));
  v_binh bigint := (SELECT id FROM public.fp_var_nhan_vien WHERE ho_va_ten ILIKE '%Văn Bình%' ORDER BY id LIMIT 1);
  v_id bigint;
BEGIN
  -- a) Phiếu giấy 27/09/2026 (ảnh mẫu): 1 khách Trung Quốc, QC xem hàng, đã về.
  INSERT INTO public.fp_farm_dang_ky_tham_quan (
    id_chi_nhanh, ngay_dang_ky, tg_bat_dau, tg_ket_thuc, muc_dich, muc_dich_khac, phuong_tien,
    nguoi_dai_dien, id_nguoi_tiep_don, trang_thai, tg_vao_thuc_te, tg_ra_thuc_te, ghi_chu
  ) VALUES (
    v_cn, '2026-09-27', '2026-09-27 09:00+07', '2026-09-27 16:09+07', ARRAY['tham_quan_nsc', 'khac'], 'QC xem hàng',
    'xe_rieng', 'A Vỹ', v_binh, 'da_ra', '2026-09-27 09:05+07', '2026-09-27 16:09+07', 'Nhập từ phiếu giấy'
  ) RETURNING id INTO v_id;
  INSERT INTO public.fp_farm_dang_ky_tham_quan_khach
    (id_phieu, stt, ho_ten, gioi_tinh, quoc_tich, so_dien_thoai, nguoi_gioi_thieu, khu_vuc_tham_quan, don_vi_lam_viec)
  VALUES (v_id, 1, 'A Vỹ', 'nam', 'Trung Quốc', '0835535879', 'Văn Thắng', 'NSC', '365');

  -- b) Đoàn du lịch 4 khách, xe công ty, chờ tham quan.
  INSERT INTO public.fp_farm_dang_ky_tham_quan (
    id_chi_nhanh, ngay_dang_ky, tg_bat_dau, tg_ket_thuc, muc_dich, phuong_tien, nguoi_dai_dien, id_nguoi_tiep_don
  ) VALUES (
    v_cn, '2026-10-10', '2026-10-12 08:30+07', '2026-10-12 11:30+07', ARRAY['tham_quan_du_lich', 'trai_nghiem_nong_nghiep'],
    'xe_cong_ty', 'Nguyễn Thị Hoa', v_binh
  ) RETURNING id INTO v_id;
  INSERT INTO public.fp_farm_dang_ky_tham_quan_khach
    (id_phieu, stt, ho_ten, gioi_tinh, quoc_tich, so_dien_thoai, nguoi_gioi_thieu, khu_vuc_tham_quan, don_vi_lam_viec)
  VALUES
    (v_id, 1, 'Nguyễn Thị Hoa', 'nu', 'Việt Nam', '0905000111', 'Phòng kinh doanh', 'Vườn sầu riêng', 'Lữ hành Tây Nguyên Xanh'),
    (v_id, 2, 'Trần Văn Nam', 'nam', 'Việt Nam', '0905000222', 'Phòng kinh doanh', 'Vườn sầu riêng', 'Lữ hành Tây Nguyên Xanh'),
    (v_id, 3, 'Lê Minh Tuấn', 'nam', 'Việt Nam', NULL, 'Phòng kinh doanh', 'NSC', 'Lữ hành Tây Nguyên Xanh'),
    (v_id, 4, 'Phạm Thu Trang', 'nu', 'Việt Nam', NULL, 'Phòng kinh doanh', 'NSC', 'Lữ hành Tây Nguyên Xanh');

  -- c) Đối tác 2 khách trải nghiệm, xe đón của farm, đang tham quan hôm nay.
  INSERT INTO public.fp_farm_dang_ky_tham_quan (
    id_chi_nhanh, ngay_dang_ky, tg_bat_dau, tg_ket_thuc, muc_dich, phuong_tien, nguoi_dai_dien, id_nguoi_tiep_don,
    trang_thai, tg_vao_thuc_te
  ) VALUES (
    v_cn, '2026-10-09', '2026-10-10 13:30+07', '2026-10-10 17:00+07', ARRAY['trai_nghiem_nong_nghiep', 'tham_quan_nsc'],
    'xe_don_nsc', 'Kim Min-jun', v_binh, 'da_vao', '2026-10-10 13:40+07'
  ) RETURNING id INTO v_id;
  INSERT INTO public.fp_farm_dang_ky_tham_quan_khach
    (id_phieu, stt, ho_ten, gioi_tinh, quoc_tich, so_dien_thoai, nguoi_gioi_thieu, khu_vuc_tham_quan, don_vi_lam_viec)
  VALUES
    (v_id, 1, 'Kim Min-jun', 'nam', 'Hàn Quốc', '0912000333', 'Văn Thắng', 'NSC, vườn ươm', 'K-Fresh Import'),
    (v_id, 2, 'Lee Soo-ah', 'nu', 'Hàn Quốc', NULL, 'Văn Thắng', 'NSC, vườn ươm', 'K-Fresh Import');

  -- d) Phiếu huỷ (khách báo không đến).
  INSERT INTO public.fp_farm_dang_ky_tham_quan (
    id_chi_nhanh, ngay_dang_ky, tg_bat_dau, tg_ket_thuc, muc_dich, phuong_tien, nguoi_dai_dien, trang_thai, ghi_chu
  ) VALUES (
    v_cn, '2026-10-03', '2026-10-05 09:00+07', '2026-10-05 10:30+07', ARRAY['tham_quan_nsc'], 'xe_rieng',
    'Đỗ Quang Huy', 'huy', 'Khách báo hoãn'
  ) RETURNING id INTO v_id;
  INSERT INTO public.fp_farm_dang_ky_tham_quan_khach
    (id_phieu, stt, ho_ten, gioi_tinh, quoc_tich, so_dien_thoai, khu_vuc_tham_quan, don_vi_lam_viec)
  VALUES (v_id, 1, 'Đỗ Quang Huy', 'nam', 'Việt Nam', '0987000444', 'NSC', 'Siêu thị Fresh Mart');
END $$;

COMMIT;

NOTIFY pgrst, 'reload schema';
