-- =============================================================================
-- Farm: Báo cáo sơ chế — thêm bảng con fp_farm_bao_cao_so_che_pham_cap (phẩm cấp)
-- Chạy một lần trên DB đã có fp_farm_bao_cao_so_che + fp_farm_bao_cao_so_che_ct.
-- Idempotent: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS.
-- Phiếu cũ: có thể 0 dòng; thêm dòng trong app.
-- Nếu bảng đã được tạo trước đó với cột ma_pham_cap (bản cũ), chạy thêm
-- docs/supabase-fp_farm_bao_cao_so_che_pham_cap_migrate_ma_to_ten.sql
-- Nếu bảng còn so_kg / ty_le_pct, sau khi deploy app mới chạy
-- docs/supabase-fp_farm_bao_cao_so_che_pham_cap_drop_derived_columns.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_so_che_pham_cap (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_so_che(id) ON DELETE CASCADE,
  ten_pham_cap text NOT NULL,
  so_tham_chieu numeric(18, 4) NOT NULL DEFAULT 0,
  so_thung numeric(18, 4) NOT NULL DEFAULT 0,
  so_thung_quy_doi numeric(18, 4) NOT NULL DEFAULT 0,
  thu_tu integer NOT NULL DEFAULT 0
);

COMMENT ON TABLE public.fp_farm_bao_cao_so_che_pham_cap IS
  'Phẩm cấp / loại thùng: nhiều dòng / phiếu; tên loại do người dùng nhập.';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.ten_pham_cap IS 'Tên loại phẩm cấp (tự do)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.so_tham_chieu IS 'Kg mỗi thùng. Tổng kg & % tính trên app.';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.thu_tu IS 'Thứ tự hiển thị trong phiếu';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_pc_bao_cao ON public.fp_farm_bao_cao_so_che_pham_cap(id_bao_cao);

DO $pcap_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che_pham_cap', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$pcap_seq$;

ALTER TABLE public.fp_farm_bao_cao_so_che_pham_cap ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che_pham_cap TO authenticated;

DROP POLICY IF EXISTS "fp_farm_bcsc_pc_select_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_insert_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_update_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_delete_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;

CREATE POLICY "fp_farm_bcsc_pc_select_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "fp_farm_bcsc_pc_insert_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_pc_update_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_pc_delete_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR DELETE TO authenticated USING (true);
