-- =============================================================================
-- Migrate: bảng fp_farm_bao_cao_so_che một tầng (cũ) → cha + fp_farm_bao_cao_so_che_ct
-- Chạy SAU khi đã có bản một bảng có cột don_vi_tinh + số liệu trên cha.
-- Nếu DB mới chỉ chạy docs/supabase-fp_farm_bao_cao_so_che.sql (2 bảng) thì KHÔNG cần file này.
--
-- Lưu ý: file này tạo `_ct` kiểu 1 dòng/phiếu (cũ). Nếu cần mô hình nhiều dòng như BCNC,
-- chạy thêm docs/supabase-fp_farm_bao_cao_so_che_ct_migrate_one_row_to_multi_row.sql
-- =============================================================================

DO $mig$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'fp_farm_bao_cao_so_che'
      AND column_name = 'don_vi_tinh'
  ) THEN
    CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_so_che_ct (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_so_che(id) ON DELETE CASCADE,
      don_vi_tinh text NOT NULL DEFAULT 'Buồng',
      sl_buong_ton_dau_ngay numeric(18, 4) NOT NULL DEFAULT 0,
      tong_buong_thu_hoach numeric(18, 4) NOT NULL DEFAULT 0,
      tong_buong_khong_so_che numeric(18, 4) NOT NULL DEFAULT 0,
      tong_buong_so_che numeric(18, 4) NOT NULL DEFAULT 0,
      sl_buong_ton_cuoi_ngay numeric(18, 4) NOT NULL DEFAULT 0
    );

    INSERT INTO public.fp_farm_bao_cao_so_che_ct (
      id_bao_cao, don_vi_tinh, sl_buong_ton_dau_ngay, tong_buong_thu_hoach,
      tong_buong_khong_so_che, tong_buong_so_che, sl_buong_ton_cuoi_ngay
    )
    SELECT
      p.id,
      COALESCE(NULLIF(trim(p.don_vi_tinh), ''), 'Buồng'),
      p.sl_buong_ton_dau_ngay,
      p.tong_buong_thu_hoach,
      p.tong_buong_khong_so_che,
      p.tong_buong_so_che,
      p.sl_buong_ton_cuoi_ngay
    FROM public.fp_farm_bao_cao_so_che p
    WHERE NOT EXISTS (SELECT 1 FROM public.fp_farm_bao_cao_so_che_ct c WHERE c.id_bao_cao = p.id);

    ALTER TABLE public.fp_farm_bao_cao_so_che
      DROP COLUMN IF EXISTS don_vi_tinh,
      DROP COLUMN IF EXISTS sl_buong_ton_dau_ngay,
      DROP COLUMN IF EXISTS tong_buong_thu_hoach,
      DROP COLUMN IF EXISTS tong_buong_khong_so_che,
      DROP COLUMN IF EXISTS tong_buong_so_che,
      DROP COLUMN IF EXISTS sl_buong_ton_cuoi_ngay;
  END IF;
END
$mig$;

DO $bcsc_mig_tail$
DECLARE
  seq text;
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'fp_farm_bao_cao_so_che_ct'
  ) THEN
    CREATE UNIQUE INDEX IF NOT EXISTS uq_fp_farm_bcsc_ct_one_row_per_phieu
      ON public.fp_farm_bao_cao_so_che_ct (id_bao_cao);
    CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_ct_bao_cao ON public.fp_farm_bao_cao_so_che_ct(id_bao_cao);

    seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che_ct', 'id');
    IF seq IS NOT NULL THEN
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
    END IF;

    ALTER TABLE public.fp_farm_bao_cao_so_che_ct ENABLE ROW LEVEL SECURITY;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che_ct TO authenticated;

    DROP POLICY IF EXISTS "fp_farm_bcsc_ct_select_auth" ON public.fp_farm_bao_cao_so_che_ct;
    DROP POLICY IF EXISTS "fp_farm_bcsc_ct_insert_auth" ON public.fp_farm_bao_cao_so_che_ct;
    DROP POLICY IF EXISTS "fp_farm_bcsc_ct_update_auth" ON public.fp_farm_bao_cao_so_che_ct;
    DROP POLICY IF EXISTS "fp_farm_bcsc_ct_delete_auth" ON public.fp_farm_bao_cao_so_che_ct;

    CREATE POLICY "fp_farm_bcsc_ct_select_auth" ON public.fp_farm_bao_cao_so_che_ct
      FOR SELECT TO authenticated USING (true);
    CREATE POLICY "fp_farm_bcsc_ct_insert_auth" ON public.fp_farm_bao_cao_so_che_ct
      FOR INSERT TO authenticated WITH CHECK (true);
    CREATE POLICY "fp_farm_bcsc_ct_update_auth" ON public.fp_farm_bao_cao_so_che_ct
      FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "fp_farm_bcsc_ct_delete_auth" ON public.fp_farm_bao_cao_so_che_ct
      FOR DELETE TO authenticated USING (true);
  END IF;
END
$bcsc_mig_tail$;
