-- =============================================================================
-- Farm: Dự báo SL đóng thùng — nhiều phiếu / ngày / chi nhánh được phép (bảng phẳng)
-- Chạy sau khi đã có fp_var_chi_nhanh, fp_var_nhan_vien (nếu FK tham chiếu)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_du_bao_sl_dong_thung (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ngay date NOT NULL,
  id_chi_nhanh bigint NOT NULL REFERENCES public.fp_var_chi_nhanh(id) ON DELETE RESTRICT,
  ten_chi_nhanh text,
  so_buong_can_mau integer NOT NULL DEFAULT 0,
  tong_can_nang_mau numeric(18, 4) NOT NULL DEFAULT 0,
  tong_buong_nhap_ke_hoach integer NOT NULL DEFAULT 0,
  ty_le_thu_hoi_ke_hoach numeric(18, 6) NOT NULL DEFAULT 0,
  quy_cach_dong_thung_ke_hoach numeric(18, 4) NOT NULL DEFAULT 0,
  tong_buong_nhap_thuc_te integer NOT NULL DEFAULT 0,
  ty_le_thu_hoi_thuc_te numeric(18, 6) NOT NULL DEFAULT 0,
  quy_cach_dong_thung_thuc_te numeric(18, 4) NOT NULL DEFAULT 0,
  ghi_chu text,
  id_nguoi_tao bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
  trang_thai text NOT NULL DEFAULT 'mo' CHECK (trang_thai IN ('mo', 'khoa')),
  tg_tao timestamptz NOT NULL DEFAULT now(),
  tg_cap_nhat timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.fp_farm_du_bao_sl_dong_thung IS 'Dự báo sản lượng đóng thùng theo ngày / chi nhánh';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.ngay IS 'Ngày phiếu';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.ten_chi_nhanh IS 'Denormalize tên chi nhánh để list không cần join';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.so_buong_can_mau IS 'Số buồng cân mẫu';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.tong_can_nang_mau IS 'Tổng cân nặng mẫu (kg)';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.tong_buong_nhap_ke_hoach IS 'Tổng buồng nhập kế hoạch';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.ty_le_thu_hoi_ke_hoach IS 'Tỷ lệ thu hồi kế hoạch (0–1, vd 0.85)';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.quy_cach_dong_thung_ke_hoach IS 'Quy cách đóng thùng kế hoạch (kg/thùng)';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.tong_buong_nhap_thuc_te IS 'Tổng buồng nhập thực tế';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.ty_le_thu_hoi_thuc_te IS 'Tỷ lệ thu hồi thực tế (0–1)';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.quy_cach_dong_thung_thuc_te IS 'Quy cách đóng thùng thực tế (kg/thùng)';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.ghi_chu IS 'Ghi chú phiếu';
COMMENT ON COLUMN public.fp_farm_du_bao_sl_dong_thung.trang_thai IS 'mo = đang mở; khoa = đã khóa';

CREATE INDEX IF NOT EXISTS idx_fp_farm_dbdt_ngay ON public.fp_farm_du_bao_sl_dong_thung(ngay DESC);
CREATE INDEX IF NOT EXISTS idx_fp_farm_dbdt_chi_nhanh ON public.fp_farm_du_bao_sl_dong_thung(id_chi_nhanh);
-- Lọc theo chi nhánh + ngày (không unique — cho phép nhiều phiếu cùng ngày)
CREATE INDEX IF NOT EXISTS idx_fp_farm_dbdt_chi_nhanh_ngay ON public.fp_farm_du_bao_sl_dong_thung(id_chi_nhanh, ngay DESC);

DO $dbdt_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_du_bao_sl_dong_thung', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$dbdt_seq$;

ALTER TABLE public.fp_farm_du_bao_sl_dong_thung ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "fp_farm_dbdt_select_auth" ON public.fp_farm_du_bao_sl_dong_thung;
DROP POLICY IF EXISTS "fp_farm_dbdt_insert_auth" ON public.fp_farm_du_bao_sl_dong_thung;
DROP POLICY IF EXISTS "fp_farm_dbdt_update_auth" ON public.fp_farm_du_bao_sl_dong_thung;
DROP POLICY IF EXISTS "fp_farm_dbdt_delete_auth" ON public.fp_farm_du_bao_sl_dong_thung;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_du_bao_sl_dong_thung TO authenticated;

CREATE POLICY "fp_farm_dbdt_select_auth" ON public.fp_farm_du_bao_sl_dong_thung
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "fp_farm_dbdt_insert_auth" ON public.fp_farm_du_bao_sl_dong_thung
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "fp_farm_dbdt_update_auth" ON public.fp_farm_du_bao_sl_dong_thung
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "fp_farm_dbdt_delete_auth" ON public.fp_farm_du_bao_sl_dong_thung
  FOR DELETE TO authenticated USING (true);
