-- =============================================================================
-- Farm: Báo cáo nhân công — chi tiết từng ô (dòng con) trên fp_farm_bao_cao_nhan_cong_ct
-- Chạy sau: docs/supabase-fp_farm_bao_cao_nhan_cong.sql
-- Migrate dữ liệu cũ (1 dòng sub / chỉ tiêu nếu có số): docs/supabase-migrate-bcnc_ct_sub-from-ct-totals.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_nhan_cong_ct_sub (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bcnc_ct bigint NOT NULL
    REFERENCES public.fp_farm_bao_cao_nhan_cong_ct(id) ON DELETE CASCADE,
  loai_chi_tieu text NOT NULL,
  thu_tu integer NOT NULL DEFAULT 0,
  sl_cong numeric(18, 4) NOT NULL DEFAULT 0,
  so_gio numeric(18, 4) NOT NULL DEFAULT 0,
  ghi_chu text,
  CONSTRAINT fp_farm_bcnc_ct_sub_loai_chk CHECK (
    loai_chi_tieu IN ('CN_NGAY', 'CN_NUA', 'TANG_CA')
  ),
  CONSTRAINT fp_farm_bcnc_ct_sub_sl_nonneg CHECK (sl_cong >= 0),
  CONSTRAINT fp_farm_bcnc_ct_sub_gio_nonneg CHECK (so_gio >= 0)
);

COMMENT ON TABLE public.fp_farm_bao_cao_nhan_cong_ct_sub IS
  'Chi tiết nhân công theo từng ô (CN ngày, CN nửa, tăng ca) trên một dòng chuyền';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct_sub.id_bcnc_ct IS
  'FK tới dòng chuyền fp_farm_bao_cao_nhan_cong_ct';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct_sub.loai_chi_tieu IS
  'CN_NGAY | CN_NUA | TANG_CA — đồng bộ cột tổng trên bảng ct';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct_sub.sl_cong IS
  'Số công nhân / SL (vd. 8, 7)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct_sub.so_gio IS
  'Số giờ (vd. 8, 7); giờ công = SUM(sl_cong * so_gio)';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcnc_ct_sub_ct
  ON public.fp_farm_bao_cao_nhan_cong_ct_sub(id_bcnc_ct);

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcnc_ct_sub_ct_loai
  ON public.fp_farm_bao_cao_nhan_cong_ct_sub(id_bcnc_ct, loai_chi_tieu, thu_tu);

DO $bcnc_sub_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_nhan_cong_ct_sub', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$bcnc_sub_seq$;

ALTER TABLE public.fp_farm_bao_cao_nhan_cong_ct_sub ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_nhan_cong_ct_sub TO authenticated;

DROP POLICY IF EXISTS "fp_farm_bcnc_ct_sub_select_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub;
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_sub_insert_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub;
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_sub_update_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub;
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_sub_delete_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub;

CREATE POLICY "fp_farm_bcnc_ct_sub_select_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "fp_farm_bcnc_ct_sub_insert_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_ct_sub_update_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_ct_sub_delete_auth" ON public.fp_farm_bao_cao_nhan_cong_ct_sub
  FOR DELETE TO authenticated USING (true);
