-- =============================================================================
-- Farm: Báo cáo sơ chế — phiếu theo ngày + chi nhánh (cha + 2 bảng con)
-- Bảng: fp_farm_bao_cao_so_che (cha), fp_farm_bao_cao_so_che_ct (chỉ tiêu buồng),
--       fp_farm_bao_cao_so_che_pham_cap (phẩm cấp / loại thùng — 6 dòng cố định / phiếu)
-- Chạy sau khi đã có fp_var_chi_nhanh, fp_var_nhan_vien (nếu FK tham chiếu)
--
-- DB đã tạo `_ct` kiểu cũ (1 dòng + jsonb): chạy
-- docs/supabase-fp_farm_bao_cao_so_che_ct_migrate_one_row_to_multi_row.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_so_che (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ngay date NOT NULL,
  id_chi_nhanh bigint NOT NULL REFERENCES public.fp_var_chi_nhanh(id) ON DELETE RESTRICT,
  ten_chi_nhanh text,
  ghi_chu text,
  id_nguoi_tao bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
  trang_thai text NOT NULL DEFAULT 'mo' CHECK (trang_thai IN ('mo', 'khoa')),
  tg_tao timestamptz NOT NULL DEFAULT now(),
  tg_cap_nhat timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.fp_farm_bao_cao_so_che IS 'Báo cáo sơ chế theo ngày / chi nhánh (phần header)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che.ngay IS 'Ngày báo cáo';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che.ten_chi_nhanh IS 'Denormalize tên chi nhánh để list không cần join';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che.trang_thai IS 'mo = đang mở; khoa = đã khóa';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_ngay ON public.fp_farm_bao_cao_so_che(ngay DESC);
CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_chi_nhanh ON public.fp_farm_bao_cao_so_che(id_chi_nhanh);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fp_farm_bcsc_chi_nhanh_ngay
  ON public.fp_farm_bao_cao_so_che (id_chi_nhanh, ngay);

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_so_che_ct (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_so_che(id) ON DELETE CASCADE,
  ma_chi_tieu text NOT NULL,
  gia_tri numeric(18, 4) NOT NULL DEFAULT 0,
  don_vi_tinh text NOT NULL DEFAULT 'Buồng',
  ghi_chu text,
  thu_tu integer NOT NULL DEFAULT 0,
  CONSTRAINT fp_farm_bcsc_ct_ma_chk CHECK (
    ma_chi_tieu IN (
      'sl_buong_ton_dau_ngay',
      'tong_buong_thu_hoach',
      'tong_buong_khong_so_che',
      'tong_buong_so_che',
      'sl_buong_ton_cuoi_ngay'
    )
  )
);

COMMENT ON TABLE public.fp_farm_bao_cao_so_che_ct IS
  'Chi tiết sơ chế: mỗi dòng một chỉ tiêu (mô hình giống fp_farm_bao_cao_nhan_cong_ct — nhiều dòng / phiếu)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.ma_chi_tieu IS 'Mã chỉ tiêu cố định (5 loại)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.gia_tri IS 'Giá trị số của chỉ tiêu';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.don_vi_tinh IS 'ĐVT theo dòng (vd. Buồng, Thùng)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.ghi_chu IS 'Ghi chú theo dòng chỉ tiêu';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.thu_tu IS 'Thứ tự hiển thị (1..5)';

CREATE UNIQUE INDEX IF NOT EXISTS uq_fp_farm_bcsc_ct_bao_cao_ma
  ON public.fp_farm_bao_cao_so_che_ct (id_bao_cao, ma_chi_tieu);

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_ct_bao_cao ON public.fp_farm_bao_cao_so_che_ct(id_bao_cao);

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_so_che_pham_cap (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_so_che(id) ON DELETE CASCADE,
  ten_pham_cap text NOT NULL,
  so_tham_chieu numeric(18, 4) NOT NULL DEFAULT 0,
  so_thung numeric(18, 4) NOT NULL DEFAULT 0,
  so_kg numeric(18, 4) NOT NULL DEFAULT 0,
  ty_le_pct numeric(7, 4) NOT NULL DEFAULT 0,
  so_thung_quy_doi numeric(18, 4) NOT NULL DEFAULT 0,
  thu_tu integer NOT NULL DEFAULT 0,
  CONSTRAINT fp_farm_bcsc_pc_ty_le_chk CHECK (ty_le_pct >= 0 AND ty_le_pct <= 100)
);

COMMENT ON TABLE public.fp_farm_bao_cao_so_che_pham_cap IS
  'Phẩm cấp / loại thùng: nhiều dòng / phiếu; tên loại do người dùng nhập.';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.ten_pham_cap IS 'Tên loại phẩm cấp (tự do)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.so_tham_chieu IS 'Cột “Số” tham chiếu trên phiếu';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.ty_le_pct IS 'Tỷ lệ % (0–100)';
COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_pham_cap.thu_tu IS 'Thứ tự hiển thị trong phiếu';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_pc_bao_cao ON public.fp_farm_bao_cao_so_che_pham_cap(id_bao_cao);

DO $bcsc_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che_ct', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che_pham_cap', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$bcsc_seq$;

-- =============================================================================
-- RLS + GRANT
-- =============================================================================

ALTER TABLE public.fp_farm_bao_cao_so_che ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fp_farm_bao_cao_so_che_ct ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fp_farm_bao_cao_so_che_pham_cap ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che_ct TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che_pham_cap TO authenticated;

-- Cha
DROP POLICY IF EXISTS "fp_farm_bcsc_select_auth" ON public.fp_farm_bao_cao_so_che;
DROP POLICY IF EXISTS "fp_farm_bcsc_insert_auth" ON public.fp_farm_bao_cao_so_che;
DROP POLICY IF EXISTS "fp_farm_bcsc_update_auth" ON public.fp_farm_bao_cao_so_che;
DROP POLICY IF EXISTS "fp_farm_bcsc_delete_auth" ON public.fp_farm_bao_cao_so_che;

CREATE POLICY "fp_farm_bcsc_select_auth" ON public.fp_farm_bao_cao_so_che
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "fp_farm_bcsc_insert_auth" ON public.fp_farm_bao_cao_so_che
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_update_auth" ON public.fp_farm_bao_cao_so_che
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_delete_auth" ON public.fp_farm_bao_cao_so_che
  FOR DELETE TO authenticated USING (true);

-- Con
DROP POLICY IF EXISTS "fp_farm_bcsc_ct_select_auth" ON public.fp_farm_bao_cao_so_che_ct;
DROP POLICY IF EXISTS "fp_farm_bcsc_ct_insert_auth" ON public.fp_farm_bao_cao_so_che_ct;
DROP POLICY IF EXISTS "fp_farm_bcsc_ct_update_auth" ON public.fp_farm_bao_cao_so_che_ct;
DROP POLICY IF EXISTS "fp_farm_bcsc_ct_delete_auth" ON public.fp_farm_bao_cao_so_che_ct;

CREATE POLICY "fp_farm_bcsc_ct_select_auth" ON public.fp_farm_bao_cao_so_che_ct
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "fp_farm_bcsc_ct_insert_auth" ON public.fp_farm_bao_cao_so_che_ct
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_ct_update_auth" ON public.fp_farm_bao_cao_so_che_ct
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_ct_delete_auth" ON public.fp_farm_bao_cao_so_che_ct
  FOR DELETE TO authenticated USING (true);

-- Phẩm cấp
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_select_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_insert_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_update_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;
DROP POLICY IF EXISTS "fp_farm_bcsc_pc_delete_auth" ON public.fp_farm_bao_cao_so_che_pham_cap;

CREATE POLICY "fp_farm_bcsc_pc_select_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "fp_farm_bcsc_pc_insert_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_pc_update_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "fp_farm_bcsc_pc_delete_auth" ON public.fp_farm_bao_cao_so_che_pham_cap
  FOR DELETE TO authenticated USING (true);
