-- =============================================================================
-- Farm: Báo cáo nhân công — phiếu theo ngày + chi tiết theo chuyền sản xuất
-- Bảng: fp_farm_bao_cao_nhan_cong (cha), fp_farm_bao_cao_nhan_cong_ct (con)
-- Chi tiết từng ô (CN ngày / CN nửa / tăng ca): docs/supabase-fp_farm_bao_cao_nhan_cong_ct_sub.sql
-- KPI / thưởng đã chuyển sang báo cáo sơ chế: docs/supabase-fp_farm_bao_cao_so_che_kpi.sql
-- Chạy sau khi đã có fp_var_chi_nhanh, fp_var_nhan_vien (nếu FK tham chiếu)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_nhan_cong (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ngay date NOT NULL,
  id_chi_nhanh bigint NOT NULL REFERENCES public.fp_var_chi_nhanh(id) ON DELETE RESTRICT,
  ten_chi_nhanh text,
  ghi_chu text,
  id_nguoi_tao bigint REFERENCES public.fp_var_nhan_vien(id) ON DELETE SET NULL,
  trang_thai text NOT NULL DEFAULT 'mo' CHECK (trang_thai IN ('mo', 'khoa')),
  tg_tao timestamptz NOT NULL DEFAULT now(),
  tg_cap_nhat timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.fp_farm_bao_cao_nhan_cong IS 'Báo cáo nhân công theo ngày / chi nhánh';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong.ngay IS 'Ngày báo cáo';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong.ten_chi_nhanh IS 'Denormalize tên chi nhánh để list không cần join';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong.ghi_chu IS 'Ghi chú phiếu; cho phép nhiều dòng (text)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong.trang_thai IS 'mo = đang mở (người tạo sửa/xóa); khoa = đã khóa (chỉ quản trị sửa/xóa trên app)';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcnc_ngay ON public.fp_farm_bao_cao_nhan_cong(ngay DESC);
CREATE INDEX IF NOT EXISTS idx_fp_farm_bcnc_chi_nhanh ON public.fp_farm_bao_cao_nhan_cong(id_chi_nhanh);

-- Một phiếu duy nhất theo cặp (chi nhánh, ngày)
CREATE UNIQUE INDEX IF NOT EXISTS uq_fp_farm_bcnc_chi_nhanh_ngay
  ON public.fp_farm_bao_cao_nhan_cong (id_chi_nhanh, ngay);

-- --- Bản đã tạo bảng trước (nullable / không unique): chạy tay sau khi làm sạch NULL trùng ---
-- UPDATE public.fp_farm_bao_cao_nhan_cong SET ... WHERE id_chi_nhanh IS NULL;
-- DELETE FROM public.fp_farm_bao_cao_nhan_cong a USING public.fp_farm_bao_cao_nhan_cong b
--   WHERE a.id > b.id AND a.id_chi_nhanh = b.id_chi_nhanh AND a.ngay = b.ngay;
-- ALTER TABLE public.fp_farm_bao_cao_nhan_cong ALTER COLUMN id_chi_nhanh SET NOT NULL;
-- (tùy) thay FK: DROP CONSTRAINT ... ; ADD CONSTRAINT ... REFERENCES ... ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_nhan_cong_ct (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_nhan_cong(id) ON DELETE CASCADE,
  loai_chuyen text NOT NULL,
  sl_cong_ngay numeric(18,4) NOT NULL DEFAULT 0,
  sl_cong_nua numeric(18,4) NOT NULL DEFAULT 0,
  sl_tang_ca numeric(18,4) NOT NULL DEFAULT 0,
  so_gio_tc numeric(18,4) NOT NULL DEFAULT 0,
  ghi_chu text,
  thu_tu integer NOT NULL DEFAULT 0,
  CONSTRAINT fp_farm_bcnc_ct_loai_chk CHECK (
    loai_chuyen IN (
      'XAN_NAI',
      'TIA_DANH_GIA',
      'CAN_TEM_DONG_THUNG',
      'KHO_HUT_CHAN_KHONG',
      'CONG_TANG_CUONG',
      'CONG_DINH_BIEN_KHONG_SAN_XUAT'
    )
  )
);

COMMENT ON TABLE public.fp_farm_bao_cao_nhan_cong_ct IS 'Chi tiết nhân công theo từng chuyền';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct.loai_chuyen IS 'Mã chuyền cố định (6 loại)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct.sl_cong_ngay IS 'SL công ngày';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct.sl_cong_nua IS 'SL công nửa';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct.sl_tang_ca IS 'SL tăng ca';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct.so_gio_tc IS 'Số giờ tăng ca';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_ct.ghi_chu IS 'Ghi chú dòng chuyền; cho phép nhiều dòng (text)';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcnc_ct_bao_cao ON public.fp_farm_bao_cao_nhan_cong_ct(id_bao_cao);

-- =============================================================================
-- Đồng bộ CHECK `loai_chuyen` (6 mã) — chạy luôn sau khi bảng con đã tồn tại.
-- Nếu DB cũ chỉ có 5 mã, INSERT chi tiết có dòng V sẽ trả HTTP 400 (violates check).
-- =============================================================================
ALTER TABLE public.fp_farm_bao_cao_nhan_cong_ct DROP CONSTRAINT IF EXISTS fp_farm_bcnc_ct_loai_chk;
ALTER TABLE public.fp_farm_bao_cao_nhan_cong_ct ADD CONSTRAINT fp_farm_bcnc_ct_loai_chk CHECK (
  loai_chuyen IN (
    'XAN_NAI',
    'TIA_DANH_GIA',
    'CAN_TEM_DONG_THUNG',
    'KHO_HUT_CHAN_KHONG',
    'CONG_TANG_CUONG',
    'CONG_DINH_BIEN_KHONG_SAN_XUAT'
  )
);

-- Quyền dùng sequence của cột IDENTITY — thiếu có thể gây lỗi khi INSERT (kèm RETURNING).
DO $bcnc_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_nhan_cong', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_nhan_cong_ct', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$bcnc_seq$;

-- =============================================================================
-- RLS + GRANT (bắt buộc nếu bảng đã ENABLE ROW LEVEL SECURITY — tránh HTTP 403)
-- Chạy toàn bộ block sau trên Supabase SQL Editor (có thể chạy lại an toàn nhờ DROP IF EXISTS).
-- App dùng user đã đăng nhập → role `authenticated` trong JWT.
-- =============================================================================

ALTER TABLE public.fp_farm_bao_cao_nhan_cong ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fp_farm_bao_cao_nhan_cong_ct ENABLE ROW LEVEL SECURITY;

-- Tên policy cũ (comment trong bản trước) — xóa nếu từng tạo tay
DROP POLICY IF EXISTS "bcnc_select" ON public.fp_farm_bao_cao_nhan_cong;
DROP POLICY IF EXISTS "bcnc_mutate" ON public.fp_farm_bao_cao_nhan_cong;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_nhan_cong TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_nhan_cong_ct TO authenticated;

-- Bảng cha
DROP POLICY IF EXISTS "fp_farm_bcnc_select_auth" ON public.fp_farm_bao_cao_nhan_cong;
DROP POLICY IF EXISTS "fp_farm_bcnc_insert_auth" ON public.fp_farm_bao_cao_nhan_cong;
DROP POLICY IF EXISTS "fp_farm_bcnc_update_auth" ON public.fp_farm_bao_cao_nhan_cong;
DROP POLICY IF EXISTS "fp_farm_bcnc_delete_auth" ON public.fp_farm_bao_cao_nhan_cong;

CREATE POLICY "fp_farm_bcnc_select_auth" ON public.fp_farm_bao_cao_nhan_cong
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "fp_farm_bcnc_insert_auth" ON public.fp_farm_bao_cao_nhan_cong
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_update_auth" ON public.fp_farm_bao_cao_nhan_cong
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_delete_auth" ON public.fp_farm_bao_cao_nhan_cong
  FOR DELETE TO authenticated USING (true);

-- Bảng con (chi tiết)
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_select_auth" ON public.fp_farm_bao_cao_nhan_cong_ct;
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_insert_auth" ON public.fp_farm_bao_cao_nhan_cong_ct;
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_update_auth" ON public.fp_farm_bao_cao_nhan_cong_ct;
DROP POLICY IF EXISTS "fp_farm_bcnc_ct_delete_auth" ON public.fp_farm_bao_cao_nhan_cong_ct;

CREATE POLICY "fp_farm_bcnc_ct_select_auth" ON public.fp_farm_bao_cao_nhan_cong_ct
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "fp_farm_bcnc_ct_insert_auth" ON public.fp_farm_bao_cao_nhan_cong_ct
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_ct_update_auth" ON public.fp_farm_bao_cao_nhan_cong_ct
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_ct_delete_auth" ON public.fp_farm_bao_cao_nhan_cong_ct
  FOR DELETE TO authenticated USING (true);

-- Gợi ý nếu vẫn HTTP 403 trên POST cha:
-- (1) Dashboard → SQL: SELECT policyname, cmd, roles FROM pg_policies WHERE schemaname = 'public' AND tablename = 'fp_farm_bao_cao_nhan_cong';
-- (2) DevTools → Application → xem có session Supabase Auth không; app dùng JWT role `authenticated`.
-- (3) Chạy lại toàn bộ block RLS + GRANT + sequence ở file này (idempotent).

-- Cập nhật tg_cap_nhat khi sửa phiếu (tuỳ chọn)
-- CREATE OR REPLACE FUNCTION public.trg_fp_farm_bcnc_touch() ...

-- Seed mẫu (tùy chọn): docs/supabase-seed-fp_farm_bao_cao_nhan_cong.sql
-- Ảnh đính kèm: docs/supabase-fp_farm_bao_cao_nhan_cong_add_hinh_anh_urls.sql
