-- =============================================================================
-- Farm: Báo cáo sơ chế — đổi `fp_farm_bao_cao_so_che_ct` sang mô hình bảng con
-- giống `fp_farm_bao_cao_nhan_cong_ct`: nhiều dòng / phiếu (mỗi dòng = một chỉ tiêu).
--
-- TRƯỚC: 1 dòng / id_bao_cao — 5 cột numeric + don_vi_tinh + (tuỳ chọn) jsonb so_lieu_row_meta.
-- SAU:  5 dòng / id_bao_cao — ma_chi_tieu (CHECK), gia_tri, don_vi_tinh, ghi_chu, thu_tu;
--       UNIQUE (id_bao_cao, ma_chi_tieu). Không còn jsonb trên bảng con.
--
-- Chạy MỘT LẦN (Supabase SQL Editor). Backup trước.
--
-- Tiền đề: đã có `fp_farm_bao_cao_so_che` + `fp_farm_bao_cao_so_che_ct` kiểu cũ.
-- Nếu chưa có cột meta: script sẽ ADD COLUMN IF NOT EXISTS trước khi migrate.
--
-- Ghi chú PG: sau `RENAME TABLE … TO …_legacy`, tên constraint (vd. fp_farm_bao_cao_so_che_ct_pkey)
-- vẫn giữ — phải đổi tên trên bảng legacy trước khi CREATE bảng mới cùng tên constraint.
--
-- Nếu lần chạy trước lỗi sau bước RENAME (chỉ còn `fp_farm_bao_cao_so_che_ct_legacy`, không còn `fp_farm_bao_cao_so_che_ct`):
--   ALTER TABLE public.fp_farm_bao_cao_so_che_ct_legacy RENAME TO fp_farm_bao_cao_so_che_ct;
--   rồi chạy lại toàn bộ file này (bản đã sửa đổi tên constraint trên legacy).
--
-- SAU KHI CHẠY: app repo đã đọc/ghi 5 dòng theo ma_chi_tieu (bao-cao-so-che-supabase.service.ts).
-- =============================================================================

DO $migrate_bcsc_ct$
DECLARE
  seq text;
BEGIN
  -- Đã migrate rồi
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'fp_farm_bao_cao_so_che_ct'
      AND column_name = 'ma_chi_tieu'
  ) THEN
    RAISE NOTICE 'fp_farm_bao_cao_so_che_ct: đã có ma_chi_tieu — bỏ qua.';
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'fp_farm_bao_cao_so_che_ct'
  ) THEN
    RAISE EXCEPTION 'Thiếu bảng fp_farm_bao_cao_so_che_ct — chạy docs/supabase-fp_farm_bao_cao_so_che.sql trước.';
  END IF;

  -- Đảm bảo có jsonb để đọc đvt/ghi chú từng dòng (nếu DB cũ chưa chạy add_so_lieu_row_meta.sql)
  ALTER TABLE public.fp_farm_bao_cao_so_che_ct
    ADD COLUMN IF NOT EXISTS so_lieu_row_meta jsonb NOT NULL DEFAULT '{}'::jsonb;

  -- Gỡ RLS policy trên bảng con
  DROP POLICY IF EXISTS "fp_farm_bcsc_ct_select_auth" ON public.fp_farm_bao_cao_so_che_ct;
  DROP POLICY IF EXISTS "fp_farm_bcsc_ct_insert_auth" ON public.fp_farm_bao_cao_so_che_ct;
  DROP POLICY IF EXISTS "fp_farm_bcsc_ct_update_auth" ON public.fp_farm_bao_cao_so_che_ct;
  DROP POLICY IF EXISTS "fp_farm_bcsc_ct_delete_auth" ON public.fp_farm_bao_cao_so_che_ct;

  DROP INDEX IF EXISTS public.uq_fp_farm_bcsc_ct_one_row_per_phieu;
  DROP INDEX IF EXISTS public.idx_fp_farm_bcsc_ct_bao_cao;

  ALTER TABLE public.fp_farm_bao_cao_so_che_ct RENAME TO fp_farm_bao_cao_so_che_ct_legacy;

  -- Đổi tên ràng buộc trên bảng legacy (RENAME TABLE không đổi tên constraint → trùng với bảng mới).
  IF EXISTS (
    SELECT 1 FROM pg_constraint c
    WHERE c.conrelid = 'public.fp_farm_bao_cao_so_che_ct_legacy'::regclass
      AND c.conname = 'fp_farm_bao_cao_so_che_ct_pkey'
  ) THEN
    EXECUTE $rn$
      ALTER TABLE public.fp_farm_bao_cao_so_che_ct_legacy
        RENAME CONSTRAINT fp_farm_bao_cao_so_che_ct_pkey TO fp_farm_bao_cao_so_che_ct_legacy_pkey
    $rn$;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_constraint c
    WHERE c.conrelid = 'public.fp_farm_bao_cao_so_che_ct_legacy'::regclass
      AND c.conname = 'fp_farm_bao_cao_so_che_ct_id_bao_cao_fkey'
  ) THEN
    EXECUTE $rn$
      ALTER TABLE public.fp_farm_bao_cao_so_che_ct_legacy
        RENAME CONSTRAINT fp_farm_bao_cao_so_che_ct_id_bao_cao_fkey TO fp_farm_bao_cao_so_che_ct_legacy_id_bao_cao_fkey
    $rn$;
  END IF;

  CREATE TABLE public.fp_farm_bao_cao_so_che_ct (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_so_che (id) ON DELETE CASCADE,
    ma_chi_tieu text NOT NULL,
    gia_tri numeric(18, 4) NOT NULL DEFAULT 0,
    don_vi_tinh text NOT NULL DEFAULT 'Buồng'::text,
    ghi_chu text,
    thu_tu integer NOT NULL DEFAULT 0,
    CONSTRAINT fp_farm_bcsc_ct_ma_chk CHECK (
      ma_chi_tieu IN (
        'sl_buong_ton_dau_ngay',
        'tong_buong_thu_hoach',
        'tong_buong_khong_so_che',
        'tong_buong_so_che',
        'sl_buong_ton_cuoi_ngay'
      )
    )
  );

  COMMENT ON TABLE public.fp_farm_bao_cao_so_che_ct IS
    'Chi tiết sơ chế: mỗi dòng một chỉ tiêu (cùng ý tưởng fp_farm_bao_cao_nhan_cong_ct).';
  COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.ma_chi_tieu IS 'Mã chỉ tiêu — khớp SoLieuRowKey trên app.';
  COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.gia_tri IS 'Giá trị số.';
  COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.don_vi_tinh IS 'ĐVT dòng.';
  COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.ghi_chu IS 'Ghi chú dòng.';
  COMMENT ON COLUMN public.fp_farm_bao_cao_so_che_ct.thu_tu IS 'Thứ tự 1..5.';

  CREATE UNIQUE INDEX uq_fp_farm_bcsc_ct_bao_cao_ma
    ON public.fp_farm_bao_cao_so_che_ct (id_bao_cao, ma_chi_tieu);

  CREATE INDEX idx_fp_farm_bcsc_ct_bao_cao ON public.fp_farm_bao_cao_so_che_ct (id_bao_cao);

  INSERT INTO public.fp_farm_bao_cao_so_che_ct (id_bao_cao, ma_chi_tieu, gia_tri, don_vi_tinh, ghi_chu, thu_tu)
  SELECT
    l.id_bao_cao,
    m.ma_chi_tieu,
    CASE m.ma_chi_tieu
      WHEN 'sl_buong_ton_dau_ngay' THEN l.sl_buong_ton_dau_ngay
      WHEN 'tong_buong_thu_hoach' THEN l.tong_buong_thu_hoach
      WHEN 'tong_buong_khong_so_che' THEN l.tong_buong_khong_so_che
      WHEN 'tong_buong_so_che' THEN l.tong_buong_so_che
      WHEN 'sl_buong_ton_cuoi_ngay' THEN l.sl_buong_ton_cuoi_ngay
    END,
    COALESCE(
      NULLIF(btrim(l.so_lieu_row_meta -> m.ma_chi_tieu ->> 'don_vi_tinh_phu'), ''),
      NULLIF(btrim(l.don_vi_tinh), ''),
      'Buồng'
    ),
    NULLIF(btrim(l.so_lieu_row_meta -> m.ma_chi_tieu ->> 'ghi_chu'), ''),
    m.thu_tu
  FROM public.fp_farm_bao_cao_so_che_ct_legacy l
  CROSS JOIN (
    VALUES
      ('sl_buong_ton_dau_ngay', 1),
      ('tong_buong_thu_hoach', 2),
      ('tong_buong_khong_so_che', 3),
      ('tong_buong_so_che', 4),
      ('sl_buong_ton_cuoi_ngay', 5)
  ) AS m(ma_chi_tieu, thu_tu);

  DROP TABLE public.fp_farm_bao_cao_so_che_ct_legacy;

  ALTER TABLE public.fp_farm_bao_cao_so_che_ct ENABLE ROW LEVEL SECURITY;

  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che_ct TO authenticated;

  CREATE POLICY "fp_farm_bcsc_ct_select_auth" ON public.fp_farm_bao_cao_so_che_ct
    FOR SELECT TO authenticated USING (true);
  CREATE POLICY "fp_farm_bcsc_ct_insert_auth" ON public.fp_farm_bao_cao_so_che_ct
    FOR INSERT TO authenticated WITH CHECK (true);
  CREATE POLICY "fp_farm_bcsc_ct_update_auth" ON public.fp_farm_bao_cao_so_che_ct
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  CREATE POLICY "fp_farm_bcsc_ct_delete_auth" ON public.fp_farm_bao_cao_so_che_ct
    FOR DELETE TO authenticated USING (true);

  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che_ct', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;

  RAISE NOTICE 'fp_farm_bao_cao_so_che_ct: migrate xong (5 dòng / phiếu).';
END
$migrate_bcsc_ct$;
