-- Bảng trạng thái tiến độ mua hàng (Quản lý nhà sơ chế - module Thiết lập đề xuất mua hàng)
-- Pattern giống fp_mh_trang_thai_thanh_toan_doi_tac

CREATE TABLE IF NOT EXISTS fp_farm_tien_do_mua_hang (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ma            text NOT NULL UNIQUE,
  ten           text NOT NULL,
  thu_tu        integer NOT NULL DEFAULT 0,
  mau           text,
  ghi_chu       text,
  trang_thai    text NOT NULL DEFAULT 'Đang hoạt động',
  tg_tao        timestamptz,
  tg_cap_nhat   timestamptz
);

-- RLS: bật và tạo policy cho user đã đăng nhập (authenticated)
ALTER TABLE fp_farm_tien_do_mua_hang ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang;
DROP POLICY IF EXISTS "Allow insert tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang;
DROP POLICY IF EXISTS "Allow update tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang;
DROP POLICY IF EXISTS "Allow delete tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang;

CREATE POLICY "Allow select tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow update tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow delete tien_do_mua_hang_farm" ON fp_farm_tien_do_mua_hang
  FOR DELETE TO authenticated USING (true);

-- Trigger cập nhật tg_cap_nhat
CREATE OR REPLACE FUNCTION fp_farm_tien_do_mua_hang_set_timestamps()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.tg_tao      := COALESCE(NEW.tg_tao, now());
    NEW.tg_cap_nhat := now();
  ELSIF TG_OP = 'UPDATE' THEN
    NEW.tg_cap_nhat := now();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_fp_farm_tien_do_mua_hang_timestamps ON fp_farm_tien_do_mua_hang;
CREATE TRIGGER tr_fp_farm_tien_do_mua_hang_timestamps
  BEFORE INSERT OR UPDATE ON fp_farm_tien_do_mua_hang
  FOR EACH ROW EXECUTE PROCEDURE fp_farm_tien_do_mua_hang_set_timestamps();

-- GRANT (bắt buộc khi bảng đã ENABLE ROW LEVEL SECURITY — thiếu thì PostgREST trả HTTP 403)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_tien_do_mua_hang TO authenticated;
DO $$
DECLARE seq text;
BEGIN
  FOR seq IN SELECT pg_get_serial_sequence('public.fp_farm_tien_do_mua_hang', 'id') LOOP
    IF seq IS NOT NULL THEN
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
    END IF;
  END LOOP;
END $$;

-- Dữ liệu mẫu: các trạng thái tiến độ mua hàng
INSERT INTO fp_farm_tien_do_mua_hang (ma, ten, thu_tu, mau, ghi_chu, trang_thai) VALUES
  ('CHUA_MUA',      'Chưa mua',      1, '#94a3b8', NULL, 'Đang hoạt động'),
  ('DA_MUA',        'Đã mua',        2, '#22c55e', NULL, 'Đang hoạt động'),
  ('TRICH_QUY',     'Trích quỹ',     3, '#0ea5e9', NULL, 'Đang hoạt động'),
  ('DIEU_CHUYEN',   'Điều chuyển',   4, '#8b5cf6', NULL, 'Đang hoạt động'),
  ('DANG_XU_LY',    'Đang xử lý',    5, '#f59e0b', NULL, 'Đang hoạt động'),
  ('TRAO_DOI',      'Trao đổi',      6, '#06b6d4', NULL, 'Đang hoạt động'),
  ('TU_CHOI',       'Từ chối',       7, '#ef4444', NULL, 'Đang hoạt động'),
  ('VP_DIEU_VE',    'VP điều về',    8, '#ec4899', NULL, 'Đang hoạt động')
ON CONFLICT (ma) DO NOTHING;
