-- =============================================================================
-- Farm: Báo cáo sơ chế — bảng con Đánh giá KPI / thưởng
-- FK: fp_farm_bao_cao_so_che(id). Chạy sau docs/supabase-fp_farm_bao_cao_so_che.sql
-- Dữ liệu cũ trên fp_farm_bao_cao_nhan_cong_kpi: xem docs/supabase-migrate-bcnc_kpi-to-bcsc_kpi.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_so_che_kpi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_so_che(id) ON DELETE CASCADE,
  thu_tu integer NOT NULL DEFAULT 0,
  ten_hang_muc text NOT NULL,
  don_vi_tinh text,
  muc_tieu text,
  thuc_te text,
  phan_tram numeric(18, 4),
  danh_gia text,
  tien_thuong numeric(18, 2) NOT NULL DEFAULT 0,
  ghi_chu text
);

COMMENT ON TABLE public.fp_farm_bao_cao_so_che_kpi IS 'Đánh giá KPI / thưởng theo phiếu báo cáo sơ chế';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcsc_kpi_bao_cao ON public.fp_farm_bao_cao_so_che_kpi(id_bao_cao);

DO $bcsc_kpi_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_so_che_kpi', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$bcsc_kpi_seq$;

ALTER TABLE public.fp_farm_bao_cao_so_che_kpi ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_so_che_kpi TO authenticated;

DROP POLICY IF EXISTS "fp_farm_bcsc_kpi_select_auth" ON public.fp_farm_bao_cao_so_che_kpi;
DROP POLICY IF EXISTS "fp_farm_bcsc_kpi_insert_auth" ON public.fp_farm_bao_cao_so_che_kpi;
DROP POLICY IF EXISTS "fp_farm_bcsc_kpi_update_auth" ON public.fp_farm_bao_cao_so_che_kpi;
DROP POLICY IF EXISTS "fp_farm_bcsc_kpi_delete_auth" ON public.fp_farm_bao_cao_so_che_kpi;

CREATE POLICY "fp_farm_bcsc_kpi_select_auth" ON public.fp_farm_bao_cao_so_che_kpi
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "fp_farm_bcsc_kpi_insert_auth" ON public.fp_farm_bao_cao_so_che_kpi
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "fp_farm_bcsc_kpi_update_auth" ON public.fp_farm_bao_cao_so_che_kpi
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "fp_farm_bcsc_kpi_delete_auth" ON public.fp_farm_bao_cao_so_che_kpi
  FOR DELETE TO authenticated USING (true);
