-- =============================================================================
-- Quản lý hợp đồng (Mua hàng) – bảng cha fp_mh_hop_dong + bảng con fp_mh_hop_dong_ct
-- (lịch sử thanh toán / đợt). Chạy trong Supabase Dashboard → SQL Editor.
-- NCC: fp_mh_danh_sach_doi_tac; người tạo: fp_var_nhan_vien; chi nhánh: fp_var_chi_nhanh
-- =============================================================================

DROP TABLE IF EXISTS fp_mh_hop_dong_ct;
DROP TABLE IF EXISTS fp_mh_hop_dong;

-- Bảng cha: hợp đồng
CREATE TABLE fp_mh_hop_dong (
  id                     bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ngay                   date,
  id_nha_cung_cap        bigint NOT NULL REFERENCES fp_mh_danh_sach_doi_tac(id),
  ten_nha_cung_cap       text,
  ma_hop_dong            text NOT NULL,
  ten_hop_dong           text,
  noi_dung               text,
  so_luong_cay           numeric(18, 4),
  don_gia                numeric(18, 2),
  thanh_tien             numeric(18, 2),
  trang_thai             text NOT NULL DEFAULT 'Đang thực hiện',
  ghi_chu                text,
  id_nguoi_tao           bigint REFERENCES fp_var_nhan_vien(id),
  tg_tao                 timestamptz DEFAULT now(),
  tg_cap_nhat            timestamptz DEFAULT now()
);

COMMENT ON TABLE fp_mh_hop_dong IS 'Hợp đồng mua hàng (header)';
COMMENT ON COLUMN fp_mh_hop_dong.id_nha_cung_cap IS 'Nhà cung cấp → fp_mh_danh_sach_doi_tac(id)';
COMMENT ON COLUMN fp_mh_hop_dong.ten_nha_cung_cap IS 'Tên NCC denormalize khi lưu';
COMMENT ON COLUMN fp_mh_hop_dong.noi_dung IS 'Nội dung hợp đồng (long text)';
COMMENT ON COLUMN fp_mh_hop_dong.trang_thai IS 'Đang thực hiện | Đã thanh lý';

CREATE UNIQUE INDEX idx_fp_mh_hop_dong_ma ON fp_mh_hop_dong(ma_hop_dong);
CREATE INDEX idx_fp_mh_hop_dong_ngay ON fp_mh_hop_dong(ngay);
CREATE INDEX idx_fp_mh_hop_dong_ncc ON fp_mh_hop_dong(id_nha_cung_cap);
CREATE INDEX idx_fp_mh_hop_dong_trang_thai ON fp_mh_hop_dong(trang_thai);
CREATE INDEX idx_fp_mh_hop_dong_nguoi_tao ON fp_mh_hop_dong(id_nguoi_tao);

-- Bảng con: lịch sử thanh toán / đợt
CREATE TABLE fp_mh_hop_dong_ct (
  id                     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  id_hop_dong            bigint NOT NULL REFERENCES fp_mh_hop_dong(id) ON DELETE CASCADE,
  ngay                   date,
  ten_dot                text,
  so_tien                numeric(18, 2),
  so_cay_thuc_nhan       numeric(18, 4),
  ghi_chu                text,
  id_chi_nhanh           bigint REFERENCES fp_var_chi_nhanh(id),
  id_nguoi_tao           bigint REFERENCES fp_var_nhan_vien(id),
  tg_tao                 timestamptz DEFAULT now(),
  tg_cap_nhat            timestamptz DEFAULT now()
);

COMMENT ON TABLE fp_mh_hop_dong_ct IS 'Lịch sử thanh toán / đợt (Cọc HĐ, TT lần 1, …)';
COMMENT ON COLUMN fp_mh_hop_dong_ct.ten_dot IS 'Tên đợt thanh toán';
COMMENT ON COLUMN fp_mh_hop_dong_ct.id_chi_nhanh IS 'Chi nhánh → fp_var_chi_nhanh(id)';

CREATE INDEX idx_fp_mh_hop_dong_ct_id_hd ON fp_mh_hop_dong_ct(id_hop_dong);
CREATE INDEX idx_fp_mh_hop_dong_ct_ngay ON fp_mh_hop_dong_ct(ngay);
CREATE INDEX idx_fp_mh_hop_dong_ct_cn ON fp_mh_hop_dong_ct(id_chi_nhanh);

-- Trigger tg_cap_nhat
CREATE OR REPLACE FUNCTION fp_mh_hop_dong_tg_cap_nhat()
RETURNS TRIGGER AS $$
BEGIN
  NEW.tg_cap_nhat = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_fp_mh_hop_dong_tg_cap_nhat
  BEFORE UPDATE ON fp_mh_hop_dong
  FOR EACH ROW EXECUTE PROCEDURE fp_mh_hop_dong_tg_cap_nhat();

CREATE OR REPLACE FUNCTION fp_mh_hop_dong_ct_tg_cap_nhat()
RETURNS TRIGGER AS $$
BEGIN
  NEW.tg_cap_nhat = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_fp_mh_hop_dong_ct_tg_cap_nhat
  BEFORE UPDATE ON fp_mh_hop_dong_ct
  FOR EACH ROW EXECUTE PROCEDURE fp_mh_hop_dong_ct_tg_cap_nhat();

-- =============================================================================
-- RLS
-- =============================================================================

ALTER TABLE fp_mh_hop_dong ENABLE ROW LEVEL SECURITY;
ALTER TABLE fp_mh_hop_dong_ct ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow select hop_dong" ON fp_mh_hop_dong
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert hop_dong" ON fp_mh_hop_dong
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow update hop_dong" ON fp_mh_hop_dong
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow delete hop_dong" ON fp_mh_hop_dong
  FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow select hop_dong_ct" ON fp_mh_hop_dong_ct
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert hop_dong_ct" ON fp_mh_hop_dong_ct
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow update hop_dong_ct" ON fp_mh_hop_dong_ct
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow delete hop_dong_ct" ON fp_mh_hop_dong_ct
  FOR DELETE TO authenticated USING (true);
