-- =============================================================================
-- Farm: Báo cáo nhân công — bảng con Đánh giá KPI (thưởng công nhân / KPI ngày)
-- FK: fp_farm_bao_cao_nhan_cong(id). Chạy sau docs/supabase-fp_farm_bao_cao_nhan_cong.sql
-- - tien_thuong: dương = thưởng, âm = trừ
-- - phan_tram: kiểu số (numeric), thang 0–100 (85 = 85%); NULL nếu dòng không có %
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.fp_farm_bao_cao_nhan_cong_kpi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_bao_cao bigint NOT NULL REFERENCES public.fp_farm_bao_cao_nhan_cong(id) ON DELETE CASCADE,
  thu_tu integer NOT NULL DEFAULT 0,
  ten_hang_muc text NOT NULL,
  don_vi_tinh text,
  muc_tieu text,
  thuc_te text,
  phan_tram numeric(18, 4),
  danh_gia text,
  tien_thuong numeric(18, 2) NOT NULL DEFAULT 0,
  ghi_chu text
);

COMMENT ON TABLE public.fp_farm_bao_cao_nhan_cong_kpi IS 'Đánh giá KPI / thưởng theo phiếu báo cáo nhân công';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.id_bao_cao IS 'Phiếu báo cáo nhân công';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.thu_tu IS 'Thứ tự hiển thị (STT)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.ten_hang_muc IS 'Hạng mục KPI';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.don_vi_tinh IS 'Đơn vị tính (Thùng, %, …)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.muc_tieu IS 'Mục tiêu (hiển thị / nhập dạng text nếu là khoảng, vd 4 đến 5)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.thuc_te IS 'Thực tế';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.phan_tram IS 'Phần trăm dạng số 0–100 (85 = 85%); NULL nếu không áp dụng';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.danh_gia IS 'Đánh giá (Đạt, Tốt, …)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.tien_thuong IS 'Tiền thưởng (+) hoặc trừ (-)';
COMMENT ON COLUMN public.fp_farm_bao_cao_nhan_cong_kpi.ghi_chu IS 'Ghi chú / quy tắc';

CREATE INDEX IF NOT EXISTS idx_fp_farm_bcnc_kpi_bao_cao ON public.fp_farm_bao_cao_nhan_cong_kpi(id_bao_cao);

DO $bcnc_kpi_seq$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.fp_farm_bao_cao_nhan_cong_kpi', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END
$bcnc_kpi_seq$;

ALTER TABLE public.fp_farm_bao_cao_nhan_cong_kpi ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fp_farm_bao_cao_nhan_cong_kpi TO authenticated;

DROP POLICY IF EXISTS "fp_farm_bcnc_kpi_select_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi;
DROP POLICY IF EXISTS "fp_farm_bcnc_kpi_insert_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi;
DROP POLICY IF EXISTS "fp_farm_bcnc_kpi_update_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi;
DROP POLICY IF EXISTS "fp_farm_bcnc_kpi_delete_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi;

CREATE POLICY "fp_farm_bcnc_kpi_select_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "fp_farm_bcnc_kpi_insert_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_kpi_update_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "fp_farm_bcnc_kpi_delete_auth" ON public.fp_farm_bao_cao_nhan_cong_kpi
  FOR DELETE TO authenticated USING (true);
