-- =====================================================================
-- BƯỚC 4 — SCHEMA CHO AUTH SELF-HOST (chỉ chạy trên fpfarm ở VPS)
--
--   psql "$VPS_DB_URL" -v ON_ERROR_STOP=1 \
--     -v auth_service_password="$AUTH_SERVICE_DB_PASSWORD" \
--     -f docs/vps-04-auth-schema.sql
--
-- Chạy SAU docs/vps-03-cleanup-after-restore.sql.
--
-- Tạo phần DB cho auth-service thay Supabase Auth:
--   - Role `auth_service`: chỉ EXECUTE được các RPC dưới đây, KHÔNG có quyền bảng.
--   - Bảng phiên (refresh token) + bảng đếm lần đăng nhập sai.
--   - RPC đăng nhập mật khẩu / đăng nhập Google / làm mới / thu hồi.
--   - Thu hồi phiên tự động khi nhân viên chuyển sang Nghỉ việc.
--   - Đóng lỗ hổng `anon` trên fp_hr_nhom_phieu_hanh_chinh.
--
-- Kế hoạch: docs/VPS_POSTGREST_PLAN.md
--
-- Idempotent — chạy lại nhiều lần vô hại.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0) GUARD
-- ---------------------------------------------------------------------
DO $$
BEGIN
  IF current_database() <> 'fpfarm' THEN
    RAISE EXCEPTION 'Chỉ chạy trên database `fpfarm` ở VPS, đang kết nối `%`.', current_database();
  END IF;
END $$;

-- psql không nội suy biến trong chuỗi dollar-quote (xem vps-01), nên chuyển
-- mật khẩu vào GUC của session rồi khối DO đọc lại bằng current_setting.
SELECT set_config('vps.auth_service_password', :'auth_service_password', false) <> ''
       AS da_nhan_mat_khau_auth_service;

-- ---------------------------------------------------------------------
-- 1) Role auth_service
--
--    NOINHERIT và không cấp quyền bảng nào: nếu service bị chiếm, kẻ tấn công
--    cũng chỉ gọi được đúng mấy RPC bên dưới, không SELECT thẳng bảng nào được.
--    Các RPC là SECURITY DEFINER nên chạy bằng quyền của owner.
-- ---------------------------------------------------------------------
DO $$
DECLARE
  v_pw TEXT := current_setting('vps.auth_service_password', true);
BEGIN
  IF coalesce(v_pw, '') = '' THEN
    RAISE EXCEPTION 'Thiếu -v auth_service_password=... khi gọi psql.';
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'auth_service') THEN
    EXECUTE format('ALTER ROLE auth_service WITH LOGIN NOINHERIT PASSWORD %L', v_pw);
  ELSE
    EXECUTE format('CREATE ROLE auth_service WITH LOGIN NOINHERIT PASSWORD %L', v_pw);
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO auth_service;

-- ---------------------------------------------------------------------
-- 2) Bảng phiên đăng nhập
--
--    Chỉ lưu SHA-256 của refresh token, không lưu token thô: dump DB hoặc
--    quyền đọc bảng này đều không đủ để mạo danh ai.
--
--    RLS bật mà KHÔNG có policy nào → PostgREST (anon/authenticated) không đọc
--    được dòng nào. Đây là bảng nội bộ của auth-service.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.fp_var_phien_dang_nhap (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nhan_vien_id  BIGINT      NOT NULL REFERENCES public.fp_var_nhan_vien(id) ON DELETE CASCADE,
  email         TEXT        NOT NULL,
  refresh_hash  TEXT        NOT NULL UNIQUE,
  het_han_luc   TIMESTAMPTZ NOT NULL,
  thu_hoi_luc   TIMESTAMPTZ,
  tao_luc       TIMESTAMPTZ NOT NULL DEFAULT now(),
  dung_lan_cuoi TIMESTAMPTZ,
  user_agent    TEXT,
  ip            TEXT
);

COMMENT ON TABLE public.fp_var_phien_dang_nhap IS
  'Phiên đăng nhập của auth-service. refresh_hash = SHA-256 hex của refresh token, token thô không bao giờ được lưu.';

CREATE INDEX IF NOT EXISTS fp_var_phien_dang_nhap_email_idx
  ON public.fp_var_phien_dang_nhap (email);
CREATE INDEX IF NOT EXISTS fp_var_phien_dang_nhap_con_hieu_luc_idx
  ON public.fp_var_phien_dang_nhap (het_han_luc)
  WHERE thu_hoi_luc IS NULL;

ALTER TABLE public.fp_var_phien_dang_nhap ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.fp_var_phien_dang_nhap FROM anon, authenticated;

-- ---------------------------------------------------------------------
-- 3) Đếm lần đăng nhập sai (chống dò mật khẩu)
--
--    Supabase Auth trước đây lo phần này. Tự host thì phải tự làm, không thì
--    endpoint đăng nhập là chỗ thử mật khẩu không giới hạn.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.fp_var_lan_dang_nhap_sai (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT        NOT NULL,
  ip    TEXT,
  luc   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS fp_var_lan_dang_nhap_sai_email_luc_idx
  ON public.fp_var_lan_dang_nhap_sai (email, luc DESC);

ALTER TABLE public.fp_var_lan_dang_nhap_sai ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.fp_var_lan_dang_nhap_sai FROM anon, authenticated;

-- Ngưỡng chặn: quá 10 lần sai trong 15 phút cho cùng một email.
CREATE OR REPLACE FUNCTION public.dang_bi_chan_dang_nhap(p_email TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*) >= 10
  FROM public.fp_var_lan_dang_nhap_sai
  WHERE email = LOWER(TRIM(coalesce(p_email, '')))
    AND luc > now() - interval '15 minutes';
$$;

REVOKE ALL ON FUNCTION public.dang_bi_chan_dang_nhap(TEXT) FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------
-- 4) Tạo phiên — dùng chung cho đăng nhập mật khẩu và đăng nhập Google
--
--    Refresh token sinh bằng gen_random_bytes (CSPRNG) ngay trong DB và chỉ
--    trả về đúng một lần cho service; DB giữ hash.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tao_phien_dang_nhap(
  p_nhan_vien_id BIGINT,
  p_email        TEXT,
  p_user_agent   TEXT,
  p_ip           TEXT,
  p_so_ngay      INT DEFAULT 30
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_token TEXT := encode(extensions.gen_random_bytes(32), 'hex');
  v_het   TIMESTAMPTZ := now() + make_interval(days => p_so_ngay);
BEGIN
  INSERT INTO public.fp_var_phien_dang_nhap
    (nhan_vien_id, email, refresh_hash, het_han_luc, user_agent, ip)
  VALUES (
    p_nhan_vien_id,
    p_email,
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    v_het,
    left(coalesce(p_user_agent, ''), 300),
    left(coalesce(p_ip, ''), 100)
  );

  RETURN jsonb_build_object('refresh_token', v_token, 'refresh_het_han', v_het);
END $$;

REVOKE ALL ON FUNCTION public.tao_phien_dang_nhap(BIGINT, TEXT, TEXT, TEXT, INT)
  FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------
-- 5) RPC đăng nhập bằng mật khẩu
--
--    Trả `phai_doi_mat_khau` trong payload vì `authenticated` đã bị thu hồi
--    quyền SELECT trên cột đó (xem vps-03) — frontend không tự đọc được.
--
--    `ly_do` phân biệt cho UI, nhưng KHÔNG tiết lộ email nào tồn tại:
--    email sai và mật khẩu sai đều trả 'sai_thong_tin'.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rpc_dang_nhap(
  p_email      TEXT,
  p_mat_khau   TEXT,
  p_user_agent TEXT DEFAULT NULL,
  p_ip         TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email TEXT := LOWER(TRIM(coalesce(p_email, '')));
  v_xac   JSONB;
  v_nv    RECORD;
  v_phien JSONB;
BEGIN
  IF public.dang_bi_chan_dang_nhap(v_email) THEN
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'bi_chan');
  END IF;

  -- Gọi được dù auth_service không có EXECUTE trên rpc_verify_mat_khau:
  -- trong thân hàm SECURITY DEFINER, current_user là owner.
  v_xac := public.rpc_verify_mat_khau(v_email, p_mat_khau);

  IF NOT coalesce((v_xac ->> 'ok')::boolean, FALSE) THEN
    INSERT INTO public.fp_var_lan_dang_nhap_sai (email, ip)
    VALUES (v_email, left(coalesce(p_ip, ''), 100));
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'sai_thong_tin');
  END IF;

  SELECT id, email, ho_va_ten, trang_thai, phai_doi_mat_khau
  INTO v_nv
  FROM public.fp_var_nhan_vien
  WHERE id = (v_xac ->> 'id')::bigint;

  IF v_nv.id IS NULL THEN
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'sai_thong_tin');
  END IF;

  IF v_nv.trang_thai = 'Nghỉ việc' THEN
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'nghi_viec');
  END IF;

  DELETE FROM public.fp_var_lan_dang_nhap_sai WHERE email = v_email;
  -- Dọn rác cơ hội: bảng này chỉ có nghĩa trong 15 phút.
  DELETE FROM public.fp_var_lan_dang_nhap_sai WHERE luc < now() - interval '1 day';

  v_phien := public.tao_phien_dang_nhap(v_nv.id, v_nv.email, p_user_agent, p_ip);

  RETURN jsonb_build_object(
    'ok', TRUE,
    'nhan_vien_id', v_nv.id,
    'email', v_nv.email,
    'ho_va_ten', v_nv.ho_va_ten,
    'phai_doi_mat_khau', v_nv.phai_doi_mat_khau
  ) || v_phien;
END $$;

REVOKE ALL ON FUNCTION public.rpc_dang_nhap(TEXT, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_dang_nhap(TEXT, TEXT, TEXT, TEXT) TO auth_service;

-- ---------------------------------------------------------------------
-- 6) RPC đăng nhập Google — KHÔNG kiểm mật khẩu
--
--    ⚠ Chỉ gọi SAU khi auth-service đã verify chữ ký RS256 của ID token với
--    khoá công khai Google và đối chiếu `aud` = client id, `email_verified`.
--    Cấp EXECUTE cho bất kỳ role nào khác auth_service là mở đường đăng nhập
--    bằng email suông.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rpc_dang_nhap_google(
  p_email      TEXT,
  p_user_agent TEXT DEFAULT NULL,
  p_ip         TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email TEXT := LOWER(TRIM(coalesce(p_email, '')));
  v_nv    RECORD;
  v_phien JSONB;
BEGIN
  SELECT id, email, ho_va_ten, trang_thai, phai_doi_mat_khau
  INTO v_nv
  FROM public.fp_var_nhan_vien
  WHERE LOWER(email) = v_email;

  IF v_nv.id IS NULL THEN
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'khong_co_ho_so');
  END IF;

  IF v_nv.trang_thai = 'Nghỉ việc' THEN
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'nghi_viec');
  END IF;

  v_phien := public.tao_phien_dang_nhap(v_nv.id, v_nv.email, p_user_agent, p_ip);

  RETURN jsonb_build_object(
    'ok', TRUE,
    'nhan_vien_id', v_nv.id,
    'email', v_nv.email,
    'ho_va_ten', v_nv.ho_va_ten,
    -- Đăng nhập Google không dùng mật khẩu nên không bắt đổi.
    'phai_doi_mat_khau', FALSE
  ) || v_phien;
END $$;

REVOKE ALL ON FUNCTION public.rpc_dang_nhap_google(TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_dang_nhap_google(TEXT, TEXT, TEXT) TO auth_service;

-- ---------------------------------------------------------------------
-- 7) RPC làm mới phiên (rotation)
--
--    Mỗi lần refresh là đổi luôn refresh token và đẩy hạn ra 30 ngày nữa, nên
--    người dùng hoạt động thường xuyên không bị đăng xuất. Token cũ sau khi
--    rotate không còn tồn tại trong bảng → dùng lại là thất bại.
--
--    Kiểm lại trang_thai ở đây là lớp chặn thứ hai cho người nghỉ việc, độc
--    lập với trigger ở mục 9.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rpc_lam_moi_phien(
  p_refresh_hash TEXT,
  p_user_agent   TEXT DEFAULT NULL,
  p_ip           TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_phien   public.fp_var_phien_dang_nhap;
  v_nv      RECORD;
  v_token   TEXT;
BEGIN
  SELECT * INTO v_phien
  FROM public.fp_var_phien_dang_nhap
  WHERE refresh_hash = coalesce(p_refresh_hash, '')
  FOR UPDATE;

  IF v_phien.id IS NULL
     OR v_phien.thu_hoi_luc IS NOT NULL
     OR v_phien.het_han_luc <= now() THEN
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'phien_khong_hop_le');
  END IF;

  SELECT id, email, trang_thai INTO v_nv
  FROM public.fp_var_nhan_vien
  WHERE id = v_phien.nhan_vien_id;

  IF v_nv.id IS NULL OR v_nv.trang_thai = 'Nghỉ việc' THEN
    UPDATE public.fp_var_phien_dang_nhap SET thu_hoi_luc = now() WHERE id = v_phien.id;
    RETURN jsonb_build_object('ok', FALSE, 'ly_do', 'nghi_viec');
  END IF;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  UPDATE public.fp_var_phien_dang_nhap
  SET refresh_hash  = encode(extensions.digest(v_token, 'sha256'), 'hex'),
      het_han_luc   = now() + interval '30 days',
      dung_lan_cuoi = now(),
      user_agent    = coalesce(left(p_user_agent, 300), user_agent),
      ip            = coalesce(left(p_ip, 100), ip)
  WHERE id = v_phien.id;

  RETURN jsonb_build_object(
    'ok', TRUE,
    'nhan_vien_id', v_nv.id,
    'email', v_nv.email,
    'refresh_token', v_token,
    'refresh_het_han', now() + interval '30 days'
  );
END $$;

REVOKE ALL ON FUNCTION public.rpc_lam_moi_phien(TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_lam_moi_phien(TEXT, TEXT, TEXT) TO auth_service;

-- ---------------------------------------------------------------------
-- 8) RPC thu hồi phiên (đăng xuất)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rpc_thu_hoi_phien(p_refresh_hash TEXT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.fp_var_phien_dang_nhap
  SET thu_hoi_luc = now()
  WHERE refresh_hash = coalesce(p_refresh_hash, '')
    AND thu_hoi_luc IS NULL;
$$;

REVOKE ALL ON FUNCTION public.rpc_thu_hoi_phien(TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_thu_hoi_phien(TEXT) TO auth_service;

-- ---------------------------------------------------------------------
-- 9) Chuyển sang Nghỉ việc là mất quyền ngay
--
--    Access token đã cấp vẫn sống tới khi hết hạn (15 phút), nhưng refresh
--    thất bại nên không gia hạn thêm được.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.thu_hoi_phien_khi_nghi_viec()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.trang_thai = 'Nghỉ việc' AND coalesce(OLD.trang_thai, '') <> 'Nghỉ việc' THEN
    UPDATE public.fp_var_phien_dang_nhap
    SET thu_hoi_luc = now()
    WHERE nhan_vien_id = NEW.id AND thu_hoi_luc IS NULL;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_thu_hoi_phien_khi_nghi_viec ON public.fp_var_nhan_vien;
CREATE TRIGGER trg_thu_hoi_phien_khi_nghi_viec
  AFTER UPDATE OF trang_thai ON public.fp_var_nhan_vien
  FOR EACH ROW
  EXECUTE FUNCTION public.thu_hoi_phien_khi_nghi_viec();

-- ---------------------------------------------------------------------
-- 10) Admin đặt lại mật khẩu người khác thì cắt luôn phiên của người đó
--
--     Bản trước (vps-03) chỉ đổi hash. Nếu một tài khoản bị nghi chiếm dụng,
--     admin đổi mật khẩu mà phiên cũ vẫn sống 30 ngày thì việc đổi vô nghĩa.
--
--     Người tự đổi mật khẩu của mình KHÔNG bị thu hồi, để luồng bắt đổi mật
--     khẩu lần đầu (phai_doi_mat_khau) không đá người ta ra ngay sau khi đổi.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rpc_set_mat_khau(
  p_nhan_vien_id BIGINT,
  p_mat_khau     TEXT,
  p_phai_doi     BOOLEAN DEFAULT FALSE
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email     TEXT;
  v_hash      TEXT;
  v_jwt_email TEXT := LOWER(NULLIF(auth.jwt() ->> 'email', ''));
BEGIN
  IF length(coalesce(p_mat_khau, '')) < 6 THEN
    RAISE EXCEPTION 'Mật khẩu phải có tối thiểu 6 ký tự.';
  END IF;

  SELECT LOWER(email) INTO v_email
  FROM public.fp_var_nhan_vien
  WHERE id = p_nhan_vien_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Không tìm thấy nhân viên id = %.', p_nhan_vien_id;
  END IF;

  IF NOT public.is_admin_current_user()
     AND (v_jwt_email IS NULL OR v_email IS DISTINCT FROM v_jwt_email) THEN
    RAISE EXCEPTION 'Không có quyền đặt mật khẩu cho nhân viên này.';
  END IF;

  v_hash := extensions.crypt(p_mat_khau, extensions.gen_salt('bf', 10));

  UPDATE public.fp_var_nhan_vien
  SET mat_khau_hash         = v_hash,
      mat_khau_cap_nhat_luc = now(),
      phai_doi_mat_khau     = p_phai_doi
  WHERE id = p_nhan_vien_id;

  IF v_email IS DISTINCT FROM v_jwt_email
     AND to_regclass('public.fp_var_phien_dang_nhap') IS NOT NULL THEN
    UPDATE public.fp_var_phien_dang_nhap
    SET thu_hoi_luc = now()
    WHERE nhan_vien_id = p_nhan_vien_id AND thu_hoi_luc IS NULL;
  END IF;
END $$;

REVOKE ALL ON FUNCTION public.rpc_set_mat_khau(BIGINT, TEXT, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rpc_set_mat_khau(BIGINT, TEXT, BOOLEAN) TO authenticated;

-- ---------------------------------------------------------------------
-- 11) Đóng lỗ hổng anon trên fp_hr_nhom_phieu_hanh_chinh
--
--     Hai policy này cho `anon` quyền ALL. Trên Supabase chúng núp sau anon
--     key, nhưng khi PostgREST ra Internet thì ai KHÔNG đăng nhập cũng đọc,
--     sửa, xoá được bảng. Bảng đã có 2 policy tương đương cho `authenticated`
--     nên xoá phần anon không làm hỏng module.
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS "Anon đọc fp_hr_nhom_phieu_hanh_chinh"
  ON public.fp_hr_nhom_phieu_hanh_chinh;
DROP POLICY IF EXISTS "Anon thêm/sửa/xóa fp_hr_nhom_phieu_hanh_chinh"
  ON public.fp_hr_nhom_phieu_hanh_chinh;
REVOKE ALL ON public.fp_hr_nhom_phieu_hanh_chinh FROM anon;

-- ---------------------------------------------------------------------
-- 12) auth-service không đi qua PostgREST nữa
--
--     vps-03 cấp EXECUTE rpc_verify_mat_khau cho `authenticator` khi chưa
--     chốt kiến trúc. Giờ service kết nối trực tiếp bằng role auth_service,
--     nên bỏ quyền đó để không còn đường gọi qua PostgREST.
-- ---------------------------------------------------------------------
REVOKE EXECUTE ON FUNCTION public.rpc_verify_mat_khau(TEXT, TEXT) FROM authenticator;

-- ---------------------------------------------------------------------
-- 13) Xác nhận
-- ---------------------------------------------------------------------
SELECT 'auth_service goi duoc rpc_dang_nhap' AS kiem_tra,
       has_function_privilege('auth_service', 'public.rpc_dang_nhap(text,text,text,text)', 'EXECUTE')::text AS gia_tri
UNION ALL
SELECT 'anon goi duoc rpc_dang_nhap (phai false)',
       has_function_privilege('anon', 'public.rpc_dang_nhap(text,text,text,text)', 'EXECUTE')::text
UNION ALL
SELECT 'anon goi duoc rpc_dang_nhap_google (phai false)',
       has_function_privilege('anon', 'public.rpc_dang_nhap_google(text,text,text)', 'EXECUTE')::text
UNION ALL
SELECT 'authenticated doc duoc bang phien (phai false)',
       has_table_privilege('authenticated', 'public.fp_var_phien_dang_nhap', 'SELECT')::text
UNION ALL
SELECT 'auth_service doc duoc bang nhan vien (phai false)',
       has_table_privilege('auth_service', 'public.fp_var_nhan_vien', 'SELECT')::text
UNION ALL
SELECT 'authenticator con goi duoc rpc_verify_mat_khau (phai false)',
       has_function_privilege('authenticator', 'public.rpc_verify_mat_khau(text,text)', 'EXECUTE')::text
UNION ALL
SELECT 'con policy anon nao khong (phai 0)',
       count(*)::text FROM pg_policies WHERE schemaname = 'public' AND roles::text LIKE '%anon%';

-- =====================================================================
-- KIỂM THỬ (chạy trong transaction rồi ROLLBACK):
--
--   BEGIN;
--   -- (a) Đăng nhập đúng → ok = true, có refresh_token
--   SELECT public.rpc_dang_nhap('<email>', '<mật khẩu>', 'psql', '127.0.0.1');
--
--   -- (b) Sai mật khẩu → ok = false, ly_do = sai_thong_tin
--   SELECT public.rpc_dang_nhap('<email>', 'sai-be-bet');
--
--   -- (c) Sai 10 lần → bị chặn
--   SELECT public.rpc_dang_nhap('<email>', 'sai') FROM generate_series(1, 10);
--   SELECT public.rpc_dang_nhap('<email>', '<mật khẩu đúng>');  -- ly_do = bi_chan
--
--   -- (d) Nghỉ việc thì phiên bị thu hồi
--   UPDATE public.fp_var_nhan_vien SET trang_thai = 'Nghỉ việc' WHERE id = <id>;
--   SELECT count(*) FROM public.fp_var_phien_dang_nhap
--   WHERE nhan_vien_id = <id> AND thu_hoi_luc IS NULL;   -- phải: 0
--   ROLLBACK;
-- =====================================================================
